/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.verizon.thingspace.exceptions;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import io.apimatic.coreinterfaces.http.Context;

/**
 * This is a model class for M403ManagementErrorException type.
 */
public class M403ManagementErrorException extends ApiException {
    private static final long serialVersionUID = -449875420103263137L;
    private String error;
    private String errorDescription;
    private String cause;

    /**
     * Initialization constructor.
     * @param   reason  The reason for throwing exception
     * @param   context The context of the API exception
     */
    public M403ManagementErrorException(String reason, Context context) {
        super(reason, context);
    }


    /**
     * Getter for Error.
     * @return Returns the String
     */
    @JsonGetter("error")
    public String getError() {
        return this.error;
    }

    /**
     * Setter for Error.
     * @param error Value for String
     */
    @JsonSetter("error")
    private void setError(String error) {
        this.error = error;
    }

    /**
     * Getter for ErrorDescription.
     * @return Returns the String
     */
    @JsonGetter("error_description")
    public String getErrorDescription() {
        return this.errorDescription;
    }

    /**
     * Setter for ErrorDescription.
     * @param errorDescription Value for String
     */
    @JsonSetter("error_description")
    private void setErrorDescription(String errorDescription) {
        this.errorDescription = errorDescription;
    }

    /**
     * Getter for Cause.
     * @return Returns the String
     */
    @JsonGetter("cause")
    public String getCauseField() {
        return this.cause;
    }

    /**
     * Setter for Cause.
     * @param causeField Value for String
     */
    @JsonSetter("cause")
    private void setCauseField(String causeField) {
        this.cause = causeField;
    }

    /**
     * Converts this M403ManagementErrorException into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "M403ManagementErrorException [" + "statusCode=" + getResponseCode() + ", message="
                + getMessage() + ", error=" + error + ", errorDescription=" + errorDescription
                + ", cause=" + cause + "]";
    }
}
