/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.verizon.thingspace.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for AccountGroupShareIndividual1 type.
 */
public class AccountGroupShareIndividual1 {
    private AccountGroupShareFilterCriteria accountGroupShareIndividual;

    /**
     * Default constructor.
     */
    public AccountGroupShareIndividual1() {
    }

    /**
     * Initialization constructor.
     * @param  accountGroupShareIndividual  AccountGroupShareFilterCriteria value for
     *         accountGroupShareIndividual.
     */
    public AccountGroupShareIndividual1(
            AccountGroupShareFilterCriteria accountGroupShareIndividual) {
        this.accountGroupShareIndividual = accountGroupShareIndividual;
    }

    /**
     * Getter for AccountGroupShareIndividual.
     * @return Returns the AccountGroupShareFilterCriteria
     */
    @JsonGetter("accountGroupShareIndividual")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public AccountGroupShareFilterCriteria getAccountGroupShareIndividual() {
        return accountGroupShareIndividual;
    }

    /**
     * Setter for AccountGroupShareIndividual.
     * @param accountGroupShareIndividual Value for AccountGroupShareFilterCriteria
     */
    @JsonSetter("accountGroupShareIndividual")
    public void setAccountGroupShareIndividual(AccountGroupShareFilterCriteria accountGroupShareIndividual) {
        this.accountGroupShareIndividual = accountGroupShareIndividual;
    }

    /**
     * Converts this AccountGroupShareIndividual1 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "AccountGroupShareIndividual1 [" + "accountGroupShareIndividual="
                + accountGroupShareIndividual + "]";
    }

    /**
     * Builds a new {@link AccountGroupShareIndividual1.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link AccountGroupShareIndividual1.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .accountGroupShareIndividual(getAccountGroupShareIndividual());
        return builder;
    }

    /**
     * Class to build instances of {@link AccountGroupShareIndividual1}.
     */
    public static class Builder {
        private AccountGroupShareFilterCriteria accountGroupShareIndividual;



        /**
         * Setter for accountGroupShareIndividual.
         * @param  accountGroupShareIndividual  AccountGroupShareFilterCriteria value for
         *         accountGroupShareIndividual.
         * @return Builder
         */
        public Builder accountGroupShareIndividual(
                AccountGroupShareFilterCriteria accountGroupShareIndividual) {
            this.accountGroupShareIndividual = accountGroupShareIndividual;
            return this;
        }

        /**
         * Builds a new {@link AccountGroupShareIndividual1} object using the set fields.
         * @return {@link AccountGroupShareIndividual1}
         */
        public AccountGroupShareIndividual1 build() {
            return new AccountGroupShareIndividual1(accountGroupShareIndividual);
        }
    }
}
