/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.verizon.thingspace.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for AccountGroupShareAction type.
 */
public class AccountGroupShareAction {
    private Notify notify;

    /**
     * Default constructor.
     */
    public AccountGroupShareAction() {
    }

    /**
     * Initialization constructor.
     * @param  notify  Notify value for notify.
     */
    public AccountGroupShareAction(
            Notify notify) {
        this.notify = notify;
    }

    /**
     * Getter for Notify.
     * @return Returns the Notify
     */
    @JsonGetter("notify")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Notify getNotify() {
        return notify;
    }

    /**
     * Setter for Notify.
     * @param notify Value for Notify
     */
    @JsonSetter("notify")
    public void setNotify(Notify notify) {
        this.notify = notify;
    }

    /**
     * Converts this AccountGroupShareAction into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "AccountGroupShareAction [" + "notify=" + notify + "]";
    }

    /**
     * Builds a new {@link AccountGroupShareAction.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link AccountGroupShareAction.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .notify(getNotify());
        return builder;
    }

    /**
     * Class to build instances of {@link AccountGroupShareAction}.
     */
    public static class Builder {
        private Notify notify;



        /**
         * Setter for notify.
         * @param  notify  Notify value for notify.
         * @return Builder
         */
        public Builder notify(Notify notify) {
            this.notify = notify;
            return this;
        }

        /**
         * Builds a new {@link AccountGroupShareAction} object using the set fields.
         * @return {@link AccountGroupShareAction}
         */
        public AccountGroupShareAction build() {
            return new AccountGroupShareAction(notify);
        }
    }
}
