/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.verizon.thingspace.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for CauseCodeChoice1 type.
 */
public class CauseCodeChoice1 {
    private int accident2;

    /**
     * Default constructor.
     */
    public CauseCodeChoice1() {
    }

    /**
     * Initialization constructor.
     * @param  accident2  int value for accident2.
     */
    @JsonCreator
    public CauseCodeChoice1(
            @JsonProperty("accident2") int accident2) {
        this.accident2 = accident2;
    }

    /**
     * Getter for Accident2.
     * The value shall be set to: - 0 `unavailable` - in case the information on the sub cause of
     * the accident is unavailable, - 1 `multiVehicleAccident` - in case more than two vehicles are
     * involved in accident, - 2 `heavyAccident` - in case the airbag of the vehicle involved in the
     * accident is triggered, * the accident requires important rescue and/or recovery work, - 3
     * `accidentInvolvingLorry` - in case the accident involves a lorry, - 4 `accidentInvolvingBus`
     * - in case the accident involves a bus, - 5 `accidentInvolvingHazardousMaterials`- in case the
     * accident involves hazardous material, - 6 `accidentOnOppositeLane` - in case the accident
     * happens on opposite lanes, - 7 `unsecuredAccident` - in case the accident is not secured, - 8
     * `assistanceRequested` - in case rescue and assistance are requested, - 9-255 - reserved for
     * future usage.
     * @return Returns the int
     */
    @JsonGetter("accident2")
    public int getAccident2() {
        return accident2;
    }

    /**
     * Setter for Accident2.
     * The value shall be set to: - 0 `unavailable` - in case the information on the sub cause of
     * the accident is unavailable, - 1 `multiVehicleAccident` - in case more than two vehicles are
     * involved in accident, - 2 `heavyAccident` - in case the airbag of the vehicle involved in the
     * accident is triggered, * the accident requires important rescue and/or recovery work, - 3
     * `accidentInvolvingLorry` - in case the accident involves a lorry, - 4 `accidentInvolvingBus`
     * - in case the accident involves a bus, - 5 `accidentInvolvingHazardousMaterials`- in case the
     * accident involves hazardous material, - 6 `accidentOnOppositeLane` - in case the accident
     * happens on opposite lanes, - 7 `unsecuredAccident` - in case the accident is not secured, - 8
     * `assistanceRequested` - in case rescue and assistance are requested, - 9-255 - reserved for
     * future usage.
     * @param accident2 Value for int
     */
    @JsonSetter("accident2")
    public void setAccident2(int accident2) {
        this.accident2 = accident2;
    }

    /**
     * Converts this CauseCodeChoice1 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "CauseCodeChoice1 [" + "accident2=" + accident2 + "]";
    }

    /**
     * Builds a new {@link CauseCodeChoice1.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link CauseCodeChoice1.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(accident2);
        return builder;
    }

    /**
     * Class to build instances of {@link CauseCodeChoice1}.
     */
    public static class Builder {
        private int accident2;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  accident2  int value for accident2.
         */
        public Builder(int accident2) {
            this.accident2 = accident2;
        }

        /**
         * Setter for accident2.
         * @param  accident2  int value for accident2.
         * @return Builder
         */
        public Builder accident2(int accident2) {
            this.accident2 = accident2;
            return this;
        }

        /**
         * Builds a new {@link CauseCodeChoice1} object using the set fields.
         * @return {@link CauseCodeChoice1}
         */
        public CauseCodeChoice1 build() {
            return new CauseCodeChoice1(accident2);
        }
    }
}
