/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.verizon.thingspace.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for Cinders type.
 */
public class Cinders {
    private Type10Enum type;

    /**
     * Default constructor.
     */
    public Cinders() {
    }

    /**
     * Initialization constructor.
     * @param  type  Type10Enum value for type.
     */
    public Cinders(
            Type10Enum type) {
        this.type = type;
    }

    /**
     * Getter for Type.
     * Indicates the type of cinders.
     * @return Returns the Type10Enum
     */
    @JsonGetter("type")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Type10Enum getType() {
        return type;
    }

    /**
     * Setter for Type.
     * Indicates the type of cinders.
     * @param type Value for Type10Enum
     */
    @JsonSetter("type")
    public void setType(Type10Enum type) {
        this.type = type;
    }

    /**
     * Converts this Cinders into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Cinders [" + "type=" + type + "]";
    }

    /**
     * Builds a new {@link Cinders.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Cinders.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .type(getType());
        return builder;
    }

    /**
     * Class to build instances of {@link Cinders}.
     */
    public static class Builder {
        private Type10Enum type;



        /**
         * Setter for type.
         * @param  type  Type10Enum value for type.
         * @return Builder
         */
        public Builder type(Type10Enum type) {
            this.type = type;
            return this;
        }

        /**
         * Builds a new {@link Cinders} object using the set fields.
         * @return {@link Cinders}
         */
        public Cinders build() {
            return new Cinders(type);
        }
    }
}
