/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.verizon.thingspace.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.UUID;

/**
 * This is a model class for ClientPersistenceResponse type.
 */
public class ClientPersistenceResponse {
    private UUID deviceID;
    private Certificate certificate;
    private EtxClientTypeEnum clientType;
    private ClientSubtypeEnum clientSubtype;
    private String vendorID;

    /**
     * Default constructor.
     */
    public ClientPersistenceResponse() {
    }

    /**
     * Initialization constructor.
     * @param  deviceID  UUID value for deviceID.
     * @param  certificate  Certificate value for certificate.
     * @param  clientType  EtxClientTypeEnum value for clientType.
     * @param  clientSubtype  ClientSubtypeEnum value for clientSubtype.
     * @param  vendorID  String value for vendorID.
     */
    public ClientPersistenceResponse(
            UUID deviceID,
            Certificate certificate,
            EtxClientTypeEnum clientType,
            ClientSubtypeEnum clientSubtype,
            String vendorID) {
        this.deviceID = deviceID;
        this.certificate = certificate;
        this.clientType = clientType;
        this.clientSubtype = clientSubtype;
        this.vendorID = vendorID;
    }

    /**
     * Getter for DeviceID.
     * The generated ID (UUID v4) for the device. It can be used as: - the MQTT Client ID when
     * connecting to the Message Exchange system - a parameter when asking for the connection
     * endpoint - a parameter when finishing the device registration - a parameter when
     * unregistering the device
     * @return Returns the UUID
     */
    @JsonGetter("DeviceID")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public UUID getDeviceID() {
        return deviceID;
    }

    /**
     * Setter for DeviceID.
     * The generated ID (UUID v4) for the device. It can be used as: - the MQTT Client ID when
     * connecting to the Message Exchange system - a parameter when asking for the connection
     * endpoint - a parameter when finishing the device registration - a parameter when
     * unregistering the device
     * @param deviceID Value for UUID
     */
    @JsonSetter("DeviceID")
    public void setDeviceID(UUID deviceID) {
        this.deviceID = deviceID;
    }

    /**
     * Getter for Certificate.
     * Structure for the credentials required to connect to the ETX MQTT Message Exchange.
     * @return Returns the Certificate
     */
    @JsonGetter("Certificate")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Certificate getCertificate() {
        return certificate;
    }

    /**
     * Setter for Certificate.
     * Structure for the credentials required to connect to the ETX MQTT Message Exchange.
     * @param certificate Value for Certificate
     */
    @JsonSetter("Certificate")
    public void setCertificate(Certificate certificate) {
        this.certificate = certificate;
    }

    /**
     * Getter for ClientType.
     * The type of the client that is to be registered. This is one of the major traffic participant
     * groups considered in V2X communication. The system uses this value to define which topics the
     * client will be able to publish and subscribe to. Values: - **Vehicle** - Vehicle with an
     * enclosure around the passengers. (Subtypes: Motorcycle, PassengerCar, Truck, Bus,
     * EmergencyVehicle, SchoolBus, MaintenanceVehicle) - **VulnerableRoadUser** - Traffic
     * participants without a protecting enclosure. (Subtypes: Bicycle, Pedestrian, Scooter) -
     * **TrafficLightController** - A Traffic light controller system. (Subtypes: NA) -
     * **InfrastructureSensor** - Sensors that are deployed in the infrastructure. (Subtypes:
     * RoadSideUnit, Camera, Lidar, Radar, InductiveLoop, MagneticSensor) - **OnboardSensor** -
     * Sensors that are onboard on a vehicle(Subtypes: Camera, Lidar, Radar) - **Software** - A
     * software system or application. (Subtypes: Platform, Application, NA)
     * @return Returns the EtxClientTypeEnum
     */
    @JsonGetter("ClientType")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public EtxClientTypeEnum getClientType() {
        return clientType;
    }

    /**
     * Setter for ClientType.
     * The type of the client that is to be registered. This is one of the major traffic participant
     * groups considered in V2X communication. The system uses this value to define which topics the
     * client will be able to publish and subscribe to. Values: - **Vehicle** - Vehicle with an
     * enclosure around the passengers. (Subtypes: Motorcycle, PassengerCar, Truck, Bus,
     * EmergencyVehicle, SchoolBus, MaintenanceVehicle) - **VulnerableRoadUser** - Traffic
     * participants without a protecting enclosure. (Subtypes: Bicycle, Pedestrian, Scooter) -
     * **TrafficLightController** - A Traffic light controller system. (Subtypes: NA) -
     * **InfrastructureSensor** - Sensors that are deployed in the infrastructure. (Subtypes:
     * RoadSideUnit, Camera, Lidar, Radar, InductiveLoop, MagneticSensor) - **OnboardSensor** -
     * Sensors that are onboard on a vehicle(Subtypes: Camera, Lidar, Radar) - **Software** - A
     * software system or application. (Subtypes: Platform, Application, NA)
     * @param clientType Value for EtxClientTypeEnum
     */
    @JsonSetter("ClientType")
    public void setClientType(EtxClientTypeEnum clientType) {
        this.clientType = clientType;
    }

    /**
     * Getter for ClientSubtype.
     * The subtype or subgroup of the client type. This further specifies the client type. For
     * example it will specify if the client is a passenger car or a truck. See the ClientType
     * description for the supported Subtypes for each client type.
     * @return Returns the ClientSubtypeEnum
     */
    @JsonGetter("ClientSubtype")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public ClientSubtypeEnum getClientSubtype() {
        return clientSubtype;
    }

    /**
     * Setter for ClientSubtype.
     * The subtype or subgroup of the client type. This further specifies the client type. For
     * example it will specify if the client is a passenger car or a truck. See the ClientType
     * description for the supported Subtypes for each client type.
     * @param clientSubtype Value for ClientSubtypeEnum
     */
    @JsonSetter("ClientSubtype")
    public void setClientSubtype(ClientSubtypeEnum clientSubtype) {
        this.clientSubtype = clientSubtype;
    }

    /**
     * Getter for VendorID.
     * The ID the vendor wants its devices to be registered under.
     * @return Returns the String
     */
    @JsonGetter("VendorID")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getVendorID() {
        return vendorID;
    }

    /**
     * Setter for VendorID.
     * The ID the vendor wants its devices to be registered under.
     * @param vendorID Value for String
     */
    @JsonSetter("VendorID")
    public void setVendorID(String vendorID) {
        this.vendorID = vendorID;
    }

    /**
     * Converts this ClientPersistenceResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ClientPersistenceResponse [" + "deviceID=" + deviceID + ", certificate="
                + certificate + ", clientType=" + clientType + ", clientSubtype=" + clientSubtype
                + ", vendorID=" + vendorID + "]";
    }

    /**
     * Builds a new {@link ClientPersistenceResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ClientPersistenceResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .deviceID(getDeviceID())
                .certificate(getCertificate())
                .clientType(getClientType())
                .clientSubtype(getClientSubtype())
                .vendorID(getVendorID());
        return builder;
    }

    /**
     * Class to build instances of {@link ClientPersistenceResponse}.
     */
    public static class Builder {
        private UUID deviceID;
        private Certificate certificate;
        private EtxClientTypeEnum clientType;
        private ClientSubtypeEnum clientSubtype;
        private String vendorID;



        /**
         * Setter for deviceID.
         * @param  deviceID  UUID value for deviceID.
         * @return Builder
         */
        public Builder deviceID(UUID deviceID) {
            this.deviceID = deviceID;
            return this;
        }

        /**
         * Setter for certificate.
         * @param  certificate  Certificate value for certificate.
         * @return Builder
         */
        public Builder certificate(Certificate certificate) {
            this.certificate = certificate;
            return this;
        }

        /**
         * Setter for clientType.
         * @param  clientType  EtxClientTypeEnum value for clientType.
         * @return Builder
         */
        public Builder clientType(EtxClientTypeEnum clientType) {
            this.clientType = clientType;
            return this;
        }

        /**
         * Setter for clientSubtype.
         * @param  clientSubtype  ClientSubtypeEnum value for clientSubtype.
         * @return Builder
         */
        public Builder clientSubtype(ClientSubtypeEnum clientSubtype) {
            this.clientSubtype = clientSubtype;
            return this;
        }

        /**
         * Setter for vendorID.
         * @param  vendorID  String value for vendorID.
         * @return Builder
         */
        public Builder vendorID(String vendorID) {
            this.vendorID = vendorID;
            return this;
        }

        /**
         * Builds a new {@link ClientPersistenceResponse} object using the set fields.
         * @return {@link ClientPersistenceResponse}
         */
        public ClientPersistenceResponse build() {
            return new ClientPersistenceResponse(deviceID, certificate, clientType, clientSubtype,
                    vendorID);
        }
    }
}
