/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.verizon.thingspace.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.verizon.thingspace.models.containers.TextPhraseOrITIS2;
import java.util.List;

/**
 * This is a model class for Content2 type.
 */
public class Content2 {
    private List<TextPhraseOrITIS2> genericSign;

    /**
     * Default constructor.
     */
    public Content2() {
    }

    /**
     * Initialization constructor.
     * @param  genericSign  List of TextPhraseOrITIS2 value for genericSign.
     */
    @JsonCreator
    public Content2(
            @JsonProperty("genericSign") List<TextPhraseOrITIS2> genericSign) {
        this.genericSign = genericSign;
    }

    /**
     * Getter for GenericSign.
     * List of MUTCD signs and directions.
     * @return Returns the List of TextPhraseOrITIS2
     */
    @JsonGetter("genericSign")
    public List<TextPhraseOrITIS2> getGenericSign() {
        return genericSign;
    }

    /**
     * Setter for GenericSign.
     * List of MUTCD signs and directions.
     * @param genericSign Value for List of TextPhraseOrITIS2
     */
    @JsonSetter("genericSign")
    public void setGenericSign(List<TextPhraseOrITIS2> genericSign) {
        this.genericSign = genericSign;
    }

    /**
     * Converts this Content2 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Content2 [" + "genericSign=" + genericSign + "]";
    }

    /**
     * Builds a new {@link Content2.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Content2.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(genericSign);
        return builder;
    }

    /**
     * Class to build instances of {@link Content2}.
     */
    public static class Builder {
        private List<TextPhraseOrITIS2> genericSign;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  genericSign  List of TextPhraseOrITIS2 value for genericSign.
         */
        public Builder(List<TextPhraseOrITIS2> genericSign) {
            this.genericSign = genericSign;
        }

        /**
         * Setter for genericSign.
         * @param  genericSign  List of TextPhraseOrITIS2 value for genericSign.
         * @return Builder
         */
        public Builder genericSign(List<TextPhraseOrITIS2> genericSign) {
            this.genericSign = genericSign;
            return this;
        }

        /**
         * Builds a new {@link Content2} object using the set fields.
         * @return {@link Content2}
         */
        public Content2 build() {
            return new Content2(genericSign);
        }
    }
}
