/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.verizon.thingspace.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for DataTrigger4 type.
 */
public class DataTrigger4 {
    private AccountLevelObject accountLevel;
    private DeviceGroupFilterCriteria deviceGroup;
    private ConditionTypeEnum conditionType;
    private ComparitorEnum comparitor;
    private Integer threshold;
    private ThresholdUnitEnum thresholdUnit;
    private RulesCycleTypeEnum cycleType;
    private AllowanceThreshold allowanceThreshold;
    private Actionobject action;

    /**
     * Default constructor.
     */
    public DataTrigger4() {
    }

    /**
     * Initialization constructor.
     * @param  accountLevel  AccountLevelObject value for accountLevel.
     * @param  deviceGroup  DeviceGroupFilterCriteria value for deviceGroup.
     * @param  conditionType  ConditionTypeEnum value for conditionType.
     * @param  comparitor  ComparitorEnum value for comparitor.
     * @param  threshold  Integer value for threshold.
     * @param  thresholdUnit  ThresholdUnitEnum value for thresholdUnit.
     * @param  cycleType  RulesCycleTypeEnum value for cycleType.
     * @param  allowanceThreshold  AllowanceThreshold value for allowanceThreshold.
     * @param  action  Actionobject value for action.
     */
    public DataTrigger4(
            AccountLevelObject accountLevel,
            DeviceGroupFilterCriteria deviceGroup,
            ConditionTypeEnum conditionType,
            ComparitorEnum comparitor,
            Integer threshold,
            ThresholdUnitEnum thresholdUnit,
            RulesCycleTypeEnum cycleType,
            AllowanceThreshold allowanceThreshold,
            Actionobject action) {
        this.accountLevel = accountLevel;
        this.deviceGroup = deviceGroup;
        this.conditionType = conditionType;
        this.comparitor = comparitor;
        this.threshold = threshold;
        this.thresholdUnit = thresholdUnit;
        this.cycleType = cycleType;
        this.allowanceThreshold = allowanceThreshold;
        this.action = action;
    }

    /**
     * Getter for AccountLevel.
     * @return Returns the AccountLevelObject
     */
    @JsonGetter("accountLevel")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public AccountLevelObject getAccountLevel() {
        return accountLevel;
    }

    /**
     * Setter for AccountLevel.
     * @param accountLevel Value for AccountLevelObject
     */
    @JsonSetter("accountLevel")
    public void setAccountLevel(AccountLevelObject accountLevel) {
        this.accountLevel = accountLevel;
    }

    /**
     * Getter for DeviceGroup.
     * @return Returns the DeviceGroupFilterCriteria
     */
    @JsonGetter("deviceGroup")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public DeviceGroupFilterCriteria getDeviceGroup() {
        return deviceGroup;
    }

    /**
     * Setter for DeviceGroup.
     * @param deviceGroup Value for DeviceGroupFilterCriteria
     */
    @JsonSetter("deviceGroup")
    public void setDeviceGroup(DeviceGroupFilterCriteria deviceGroup) {
        this.deviceGroup = deviceGroup;
    }

    /**
     * Getter for ConditionType.
     * The condition type being monitored
     * @return Returns the ConditionTypeEnum
     */
    @JsonGetter("conditionType")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public ConditionTypeEnum getConditionType() {
        return conditionType;
    }

    /**
     * Setter for ConditionType.
     * The condition type being monitored
     * @param conditionType Value for ConditionTypeEnum
     */
    @JsonSetter("conditionType")
    public void setConditionType(ConditionTypeEnum conditionType) {
        this.conditionType = conditionType;
    }

    /**
     * Getter for Comparitor.
     * The boolean of the comparison. `gt` is Greater Than, `lt` is Less Than and `eq` is Equal To
     * @return Returns the ComparitorEnum
     */
    @JsonGetter("comparitor")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public ComparitorEnum getComparitor() {
        return comparitor;
    }

    /**
     * Setter for Comparitor.
     * The boolean of the comparison. `gt` is Greater Than, `lt` is Less Than and `eq` is Equal To
     * @param comparitor Value for ComparitorEnum
     */
    @JsonSetter("comparitor")
    public void setComparitor(ComparitorEnum comparitor) {
        this.comparitor = comparitor;
    }

    /**
     * Getter for Threshold.
     * The threshold value the trigger monitors for
     * @return Returns the Integer
     */
    @JsonGetter("threshold")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Integer getThreshold() {
        return threshold;
    }

    /**
     * Setter for Threshold.
     * The threshold value the trigger monitors for
     * @param threshold Value for Integer
     */
    @JsonSetter("threshold")
    public void setThreshold(Integer threshold) {
        this.threshold = threshold;
    }

    /**
     * Getter for ThresholdUnit.
     * The units of the threshold. This can be KB, Kilobits, MB, Megabits, or GB, Gigabits
     * @return Returns the ThresholdUnitEnum
     */
    @JsonGetter("thresholdUnit")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public ThresholdUnitEnum getThresholdUnit() {
        return thresholdUnit;
    }

    /**
     * Setter for ThresholdUnit.
     * The units of the threshold. This can be KB, Kilobits, MB, Megabits, or GB, Gigabits
     * @param thresholdUnit Value for ThresholdUnitEnum
     */
    @JsonSetter("thresholdUnit")
    public void setThresholdUnit(ThresholdUnitEnum thresholdUnit) {
        this.thresholdUnit = thresholdUnit;
    }

    /**
     * Getter for CycleType.
     * The interval to monitor for the threshold. This can be Daily, Weekly or Monthly
     * @return Returns the RulesCycleTypeEnum
     */
    @JsonGetter("cycleType")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public RulesCycleTypeEnum getCycleType() {
        return cycleType;
    }

    /**
     * Setter for CycleType.
     * The interval to monitor for the threshold. This can be Daily, Weekly or Monthly
     * @param cycleType Value for RulesCycleTypeEnum
     */
    @JsonSetter("cycleType")
    public void setCycleType(RulesCycleTypeEnum cycleType) {
        this.cycleType = cycleType;
    }

    /**
     * Getter for AllowanceThreshold.
     * @return Returns the AllowanceThreshold
     */
    @JsonGetter("allowanceThreshold")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public AllowanceThreshold getAllowanceThreshold() {
        return allowanceThreshold;
    }

    /**
     * Setter for AllowanceThreshold.
     * @param allowanceThreshold Value for AllowanceThreshold
     */
    @JsonSetter("allowanceThreshold")
    public void setAllowanceThreshold(AllowanceThreshold allowanceThreshold) {
        this.allowanceThreshold = allowanceThreshold;
    }

    /**
     * Getter for Action.
     * @return Returns the Actionobject
     */
    @JsonGetter("action")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Actionobject getAction() {
        return action;
    }

    /**
     * Setter for Action.
     * @param action Value for Actionobject
     */
    @JsonSetter("action")
    public void setAction(Actionobject action) {
        this.action = action;
    }

    /**
     * Converts this DataTrigger4 into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "DataTrigger4 [" + "accountLevel=" + accountLevel + ", deviceGroup=" + deviceGroup
                + ", conditionType=" + conditionType + ", comparitor=" + comparitor + ", threshold="
                + threshold + ", thresholdUnit=" + thresholdUnit + ", cycleType=" + cycleType
                + ", allowanceThreshold=" + allowanceThreshold + ", action=" + action + "]";
    }

    /**
     * Builds a new {@link DataTrigger4.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link DataTrigger4.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .accountLevel(getAccountLevel())
                .deviceGroup(getDeviceGroup())
                .conditionType(getConditionType())
                .comparitor(getComparitor())
                .threshold(getThreshold())
                .thresholdUnit(getThresholdUnit())
                .cycleType(getCycleType())
                .allowanceThreshold(getAllowanceThreshold())
                .action(getAction());
        return builder;
    }

    /**
     * Class to build instances of {@link DataTrigger4}.
     */
    public static class Builder {
        private AccountLevelObject accountLevel;
        private DeviceGroupFilterCriteria deviceGroup;
        private ConditionTypeEnum conditionType;
        private ComparitorEnum comparitor;
        private Integer threshold;
        private ThresholdUnitEnum thresholdUnit;
        private RulesCycleTypeEnum cycleType;
        private AllowanceThreshold allowanceThreshold;
        private Actionobject action;



        /**
         * Setter for accountLevel.
         * @param  accountLevel  AccountLevelObject value for accountLevel.
         * @return Builder
         */
        public Builder accountLevel(AccountLevelObject accountLevel) {
            this.accountLevel = accountLevel;
            return this;
        }

        /**
         * Setter for deviceGroup.
         * @param  deviceGroup  DeviceGroupFilterCriteria value for deviceGroup.
         * @return Builder
         */
        public Builder deviceGroup(DeviceGroupFilterCriteria deviceGroup) {
            this.deviceGroup = deviceGroup;
            return this;
        }

        /**
         * Setter for conditionType.
         * @param  conditionType  ConditionTypeEnum value for conditionType.
         * @return Builder
         */
        public Builder conditionType(ConditionTypeEnum conditionType) {
            this.conditionType = conditionType;
            return this;
        }

        /**
         * Setter for comparitor.
         * @param  comparitor  ComparitorEnum value for comparitor.
         * @return Builder
         */
        public Builder comparitor(ComparitorEnum comparitor) {
            this.comparitor = comparitor;
            return this;
        }

        /**
         * Setter for threshold.
         * @param  threshold  Integer value for threshold.
         * @return Builder
         */
        public Builder threshold(Integer threshold) {
            this.threshold = threshold;
            return this;
        }

        /**
         * Setter for thresholdUnit.
         * @param  thresholdUnit  ThresholdUnitEnum value for thresholdUnit.
         * @return Builder
         */
        public Builder thresholdUnit(ThresholdUnitEnum thresholdUnit) {
            this.thresholdUnit = thresholdUnit;
            return this;
        }

        /**
         * Setter for cycleType.
         * @param  cycleType  RulesCycleTypeEnum value for cycleType.
         * @return Builder
         */
        public Builder cycleType(RulesCycleTypeEnum cycleType) {
            this.cycleType = cycleType;
            return this;
        }

        /**
         * Setter for allowanceThreshold.
         * @param  allowanceThreshold  AllowanceThreshold value for allowanceThreshold.
         * @return Builder
         */
        public Builder allowanceThreshold(AllowanceThreshold allowanceThreshold) {
            this.allowanceThreshold = allowanceThreshold;
            return this;
        }

        /**
         * Setter for action.
         * @param  action  Actionobject value for action.
         * @return Builder
         */
        public Builder action(Actionobject action) {
            this.action = action;
            return this;
        }

        /**
         * Builds a new {@link DataTrigger4} object using the set fields.
         * @return {@link DataTrigger4}
         */
        public DataTrigger4 build() {
            return new DataTrigger4(accountLevel, deviceGroup, conditionType, comparitor, threshold,
                    thresholdUnit, cycleType, allowanceThreshold, action);
        }
    }
}
