/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.verizon.thingspace.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for DescriptionOfRoadSurfaceRock type.
 */
public class DescriptionOfRoadSurfaceRock {
    private Rock rock;

    /**
     * Default constructor.
     */
    public DescriptionOfRoadSurfaceRock() {
    }

    /**
     * Initialization constructor.
     * @param  rock  Rock value for rock.
     */
    @JsonCreator
    public DescriptionOfRoadSurfaceRock(
            @JsonProperty("rock") Rock rock) {
        this.rock = rock;
    }

    /**
     * Getter for Rock.
     * Indicates the surface of the roadway is rock.
     * @return Returns the Rock
     */
    @JsonGetter("rock")
    public Rock getRock() {
        return rock;
    }

    /**
     * Setter for Rock.
     * Indicates the surface of the roadway is rock.
     * @param rock Value for Rock
     */
    @JsonSetter("rock")
    public void setRock(Rock rock) {
        this.rock = rock;
    }

    /**
     * Converts this DescriptionOfRoadSurfaceRock into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "DescriptionOfRoadSurfaceRock [" + "rock=" + rock + "]";
    }

    /**
     * Builds a new {@link DescriptionOfRoadSurfaceRock.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link DescriptionOfRoadSurfaceRock.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(rock);
        return builder;
    }

    /**
     * Class to build instances of {@link DescriptionOfRoadSurfaceRock}.
     */
    public static class Builder {
        private Rock rock;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  rock  Rock value for rock.
         */
        public Builder(Rock rock) {
            this.rock = rock;
        }

        /**
         * Setter for rock.
         * @param  rock  Rock value for rock.
         * @return Builder
         */
        public Builder rock(Rock rock) {
            this.rock = rock;
            return this;
        }

        /**
         * Builds a new {@link DescriptionOfRoadSurfaceRock} object using the set fields.
         * @return {@link DescriptionOfRoadSurfaceRock}
         */
        public DescriptionOfRoadSurfaceRock build() {
            return new DescriptionOfRoadSurfaceRock(rock);
        }
    }
}
