/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.verizon.thingspace.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for Devicepropertyselection type.
 */
public class Devicepropertyselection {
    private String modelid;

    /**
     * Default constructor.
     */
    public Devicepropertyselection() {
    }

    /**
     * Initialization constructor.
     * @param  modelid  String value for modelid.
     */
    public Devicepropertyselection(
            String modelid) {
        this.modelid = modelid;
    }

    /**
     * Getter for Modelid.
     * @return Returns the String
     */
    @JsonGetter("modelid")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getModelid() {
        return modelid;
    }

    /**
     * Setter for Modelid.
     * @param modelid Value for String
     */
    @JsonSetter("modelid")
    public void setModelid(String modelid) {
        this.modelid = modelid;
    }

    /**
     * Converts this Devicepropertyselection into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Devicepropertyselection [" + "modelid=" + modelid + "]";
    }

    /**
     * Builds a new {@link Devicepropertyselection.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Devicepropertyselection.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .modelid(getModelid());
        return builder;
    }

    /**
     * Class to build instances of {@link Devicepropertyselection}.
     */
    public static class Builder {
        private String modelid;



        /**
         * Setter for modelid.
         * @param  modelid  String value for modelid.
         * @return Builder
         */
        public Builder modelid(String modelid) {
            this.modelid = modelid;
            return this;
        }

        /**
         * Builds a new {@link Devicepropertyselection} object using the set fields.
         * @return {@link Devicepropertyselection}
         */
        public Devicepropertyselection build() {
            return new Devicepropertyselection(modelid);
        }
    }
}
