/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.verizon.thingspace.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.verizon.thingspace.DateTimeHelper;
import java.time.LocalDateTime;

/**
 * This is a model class for DistributionSchedule type.
 */
public class DistributionSchedule {
    private int repeatPeriod;
    private int duration;
    private LocalDateTime startTime;

    /**
     * Default constructor.
     */
    public DistributionSchedule() {
    }

    /**
     * Initialization constructor.
     * @param  repeatPeriod  int value for repeatPeriod.
     * @param  duration  int value for duration.
     * @param  startTime  LocalDateTime value for startTime.
     */
    public DistributionSchedule(
            int repeatPeriod,
            int duration,
            LocalDateTime startTime) {
        this.repeatPeriod = repeatPeriod;
        this.duration = duration;
        this.startTime = startTime;
    }

    /**
     * Getter for RepeatPeriod.
     * The period (in seconds) that the message needs to be repeatedly send out.
     * @return Returns the int
     */
    @JsonGetter("repeatPeriod")
    public int getRepeatPeriod() {
        return repeatPeriod;
    }

    /**
     * Setter for RepeatPeriod.
     * The period (in seconds) that the message needs to be repeatedly send out.
     * @param repeatPeriod Value for int
     */
    @JsonSetter("repeatPeriod")
    public void setRepeatPeriod(int repeatPeriod) {
        this.repeatPeriod = repeatPeriod;
    }

    /**
     * Getter for Duration.
     * The amount of time (in minutes) while the messages needs to be sent out.
     * @return Returns the int
     */
    @JsonGetter("duration")
    public int getDuration() {
        return duration;
    }

    /**
     * Setter for Duration.
     * The amount of time (in minutes) while the messages needs to be sent out.
     * @param duration Value for int
     */
    @JsonSetter("duration")
    public void setDuration(int duration) {
        this.duration = duration;
    }

    /**
     * Getter for StartTime.
     * The time (in UTC) when the message transmission should be started.
     * @return Returns the LocalDateTime
     */
    @JsonGetter("startTime")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    @JsonSerialize(using = DateTimeHelper.Rfc8601DateTimeSerializer.class)
    public LocalDateTime getStartTime() {
        return startTime;
    }

    /**
     * Setter for StartTime.
     * The time (in UTC) when the message transmission should be started.
     * @param startTime Value for LocalDateTime
     */
    @JsonSetter("startTime")
    @JsonDeserialize(using = DateTimeHelper.Rfc8601DateTimeDeserializer.class)
    public void setStartTime(LocalDateTime startTime) {
        this.startTime = startTime;
    }

    /**
     * Converts this DistributionSchedule into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "DistributionSchedule [" + "repeatPeriod=" + repeatPeriod + ", duration=" + duration
                + ", startTime=" + startTime + "]";
    }

    /**
     * Builds a new {@link DistributionSchedule.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link DistributionSchedule.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(repeatPeriod, duration)
                .startTime(getStartTime());
        return builder;
    }

    /**
     * Class to build instances of {@link DistributionSchedule}.
     */
    public static class Builder {
        private int repeatPeriod;
        private int duration;
        private LocalDateTime startTime;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  repeatPeriod  int value for repeatPeriod.
         * @param  duration  int value for duration.
         */
        public Builder(int repeatPeriod, int duration) {
            this.repeatPeriod = repeatPeriod;
            this.duration = duration;
        }

        /**
         * Setter for repeatPeriod.
         * @param  repeatPeriod  int value for repeatPeriod.
         * @return Builder
         */
        public Builder repeatPeriod(int repeatPeriod) {
            this.repeatPeriod = repeatPeriod;
            return this;
        }

        /**
         * Setter for duration.
         * @param  duration  int value for duration.
         * @return Builder
         */
        public Builder duration(int duration) {
            this.duration = duration;
            return this;
        }

        /**
         * Setter for startTime.
         * @param  startTime  LocalDateTime value for startTime.
         * @return Builder
         */
        public Builder startTime(LocalDateTime startTime) {
            this.startTime = startTime;
            return this;
        }

        /**
         * Builds a new {@link DistributionSchedule} object using the set fields.
         * @return {@link DistributionSchedule}
         */
        public DistributionSchedule build() {
            return new DistributionSchedule(repeatPeriod, duration, startTime);
        }
    }
}
