/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.verizon.thingspace.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for DtoConfigurationProfileDelete type.
 */
public class DtoConfigurationProfileDelete {
    private String accountName;
    private DtoResourceidentifier resourceidentifier;

    /**
     * Default constructor.
     */
    public DtoConfigurationProfileDelete() {
    }

    /**
     * Initialization constructor.
     * @param  accountName  String value for accountName.
     * @param  resourceidentifier  DtoResourceidentifier value for resourceidentifier.
     */
    public DtoConfigurationProfileDelete(
            String accountName,
            DtoResourceidentifier resourceidentifier) {
        this.accountName = accountName;
        this.resourceidentifier = resourceidentifier;
    }

    /**
     * Getter for AccountName.
     * The numeric account name, which must include leading zeros
     * @return Returns the String
     */
    @JsonGetter("accountName")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getAccountName() {
        return accountName;
    }

    /**
     * Setter for AccountName.
     * The numeric account name, which must include leading zeros
     * @param accountName Value for String
     */
    @JsonSetter("accountName")
    public void setAccountName(String accountName) {
        this.accountName = accountName;
    }

    /**
     * Getter for Resourceidentifier.
     * @return Returns the DtoResourceidentifier
     */
    @JsonGetter("resourceidentifier")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public DtoResourceidentifier getResourceidentifier() {
        return resourceidentifier;
    }

    /**
     * Setter for Resourceidentifier.
     * @param resourceidentifier Value for DtoResourceidentifier
     */
    @JsonSetter("resourceidentifier")
    public void setResourceidentifier(DtoResourceidentifier resourceidentifier) {
        this.resourceidentifier = resourceidentifier;
    }

    /**
     * Converts this DtoConfigurationProfileDelete into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "DtoConfigurationProfileDelete [" + "accountName=" + accountName
                + ", resourceidentifier=" + resourceidentifier + "]";
    }

    /**
     * Builds a new {@link DtoConfigurationProfileDelete.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link DtoConfigurationProfileDelete.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .accountName(getAccountName())
                .resourceidentifier(getResourceidentifier());
        return builder;
    }

    /**
     * Class to build instances of {@link DtoConfigurationProfileDelete}.
     */
    public static class Builder {
        private String accountName;
        private DtoResourceidentifier resourceidentifier;



        /**
         * Setter for accountName.
         * @param  accountName  String value for accountName.
         * @return Builder
         */
        public Builder accountName(String accountName) {
            this.accountName = accountName;
            return this;
        }

        /**
         * Setter for resourceidentifier.
         * @param  resourceidentifier  DtoResourceidentifier value for resourceidentifier.
         * @return Builder
         */
        public Builder resourceidentifier(DtoResourceidentifier resourceidentifier) {
            this.resourceidentifier = resourceidentifier;
            return this;
        }

        /**
         * Builds a new {@link DtoConfigurationProfileDelete} object using the set fields.
         * @return {@link DtoConfigurationProfileDelete}
         */
        public DtoConfigurationProfileDelete build() {
            return new DtoConfigurationProfileDelete(accountName, resourceidentifier);
        }
    }
}
