/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.verizon.thingspace.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for DtoFields type.
 */
public class DtoFields {
    private String additionalProp1;
    private String additionalProp2;
    private String additionalProp3;

    /**
     * Default constructor.
     */
    public DtoFields() {
    }

    /**
     * Initialization constructor.
     * @param  additionalProp1  String value for additionalProp1.
     * @param  additionalProp2  String value for additionalProp2.
     * @param  additionalProp3  String value for additionalProp3.
     */
    public DtoFields(
            String additionalProp1,
            String additionalProp2,
            String additionalProp3) {
        this.additionalProp1 = additionalProp1;
        this.additionalProp2 = additionalProp2;
        this.additionalProp3 = additionalProp3;
    }

    /**
     * Getter for AdditionalProp1.
     * @return Returns the String
     */
    @JsonGetter("additionalProp1")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getAdditionalProp1() {
        return additionalProp1;
    }

    /**
     * Setter for AdditionalProp1.
     * @param additionalProp1 Value for String
     */
    @JsonSetter("additionalProp1")
    public void setAdditionalProp1(String additionalProp1) {
        this.additionalProp1 = additionalProp1;
    }

    /**
     * Getter for AdditionalProp2.
     * @return Returns the String
     */
    @JsonGetter("additionalProp2")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getAdditionalProp2() {
        return additionalProp2;
    }

    /**
     * Setter for AdditionalProp2.
     * @param additionalProp2 Value for String
     */
    @JsonSetter("additionalProp2")
    public void setAdditionalProp2(String additionalProp2) {
        this.additionalProp2 = additionalProp2;
    }

    /**
     * Getter for AdditionalProp3.
     * @return Returns the String
     */
    @JsonGetter("additionalProp3")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getAdditionalProp3() {
        return additionalProp3;
    }

    /**
     * Setter for AdditionalProp3.
     * @param additionalProp3 Value for String
     */
    @JsonSetter("additionalProp3")
    public void setAdditionalProp3(String additionalProp3) {
        this.additionalProp3 = additionalProp3;
    }

    /**
     * Converts this DtoFields into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "DtoFields [" + "additionalProp1=" + additionalProp1 + ", additionalProp2="
                + additionalProp2 + ", additionalProp3=" + additionalProp3 + "]";
    }

    /**
     * Builds a new {@link DtoFields.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link DtoFields.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .additionalProp1(getAdditionalProp1())
                .additionalProp2(getAdditionalProp2())
                .additionalProp3(getAdditionalProp3());
        return builder;
    }

    /**
     * Class to build instances of {@link DtoFields}.
     */
    public static class Builder {
        private String additionalProp1;
        private String additionalProp2;
        private String additionalProp3;



        /**
         * Setter for additionalProp1.
         * @param  additionalProp1  String value for additionalProp1.
         * @return Builder
         */
        public Builder additionalProp1(String additionalProp1) {
            this.additionalProp1 = additionalProp1;
            return this;
        }

        /**
         * Setter for additionalProp2.
         * @param  additionalProp2  String value for additionalProp2.
         * @return Builder
         */
        public Builder additionalProp2(String additionalProp2) {
            this.additionalProp2 = additionalProp2;
            return this;
        }

        /**
         * Setter for additionalProp3.
         * @param  additionalProp3  String value for additionalProp3.
         * @return Builder
         */
        public Builder additionalProp3(String additionalProp3) {
            this.additionalProp3 = additionalProp3;
            return this;
        }

        /**
         * Builds a new {@link DtoFields} object using the set fields.
         * @return {@link DtoFields}
         */
        public DtoFields build() {
            return new DtoFields(additionalProp1, additionalProp2, additionalProp3);
        }
    }
}
