/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.verizon.thingspace.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for DtoPatchDeviceRequest type.
 */
public class DtoPatchDeviceRequest {
    private String accountname;
    private ResourceDevice device;
    private DtoDeviceResourceIdentifier resourceidentifier;

    /**
     * Default constructor.
     */
    public DtoPatchDeviceRequest() {
    }

    /**
     * Initialization constructor.
     * @param  accountname  String value for accountname.
     * @param  device  ResourceDevice value for device.
     * @param  resourceidentifier  DtoDeviceResourceIdentifier value for resourceidentifier.
     */
    public DtoPatchDeviceRequest(
            String accountname,
            ResourceDevice device,
            DtoDeviceResourceIdentifier resourceidentifier) {
        this.accountname = accountname;
        this.device = device;
        this.resourceidentifier = resourceidentifier;
    }

    /**
     * Getter for Accountname.
     * The numeric account name, which must include leading zeros
     * @return Returns the String
     */
    @JsonGetter("accountname")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getAccountname() {
        return accountname;
    }

    /**
     * Setter for Accountname.
     * The numeric account name, which must include leading zeros
     * @param accountname Value for String
     */
    @JsonSetter("accountname")
    public void setAccountname(String accountname) {
        this.accountname = accountname;
    }

    /**
     * Getter for Device.
     * @return Returns the ResourceDevice
     */
    @JsonGetter("device")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public ResourceDevice getDevice() {
        return device;
    }

    /**
     * Setter for Device.
     * @param device Value for ResourceDevice
     */
    @JsonSetter("device")
    public void setDevice(ResourceDevice device) {
        this.device = device;
    }

    /**
     * Getter for Resourceidentifier.
     * Device identifiers, one or more are required
     * @return Returns the DtoDeviceResourceIdentifier
     */
    @JsonGetter("resourceidentifier")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public DtoDeviceResourceIdentifier getResourceidentifier() {
        return resourceidentifier;
    }

    /**
     * Setter for Resourceidentifier.
     * Device identifiers, one or more are required
     * @param resourceidentifier Value for DtoDeviceResourceIdentifier
     */
    @JsonSetter("resourceidentifier")
    public void setResourceidentifier(DtoDeviceResourceIdentifier resourceidentifier) {
        this.resourceidentifier = resourceidentifier;
    }

    /**
     * Converts this DtoPatchDeviceRequest into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "DtoPatchDeviceRequest [" + "accountname=" + accountname + ", device=" + device
                + ", resourceidentifier=" + resourceidentifier + "]";
    }

    /**
     * Builds a new {@link DtoPatchDeviceRequest.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link DtoPatchDeviceRequest.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .accountname(getAccountname())
                .device(getDevice())
                .resourceidentifier(getResourceidentifier());
        return builder;
    }

    /**
     * Class to build instances of {@link DtoPatchDeviceRequest}.
     */
    public static class Builder {
        private String accountname;
        private ResourceDevice device;
        private DtoDeviceResourceIdentifier resourceidentifier;



        /**
         * Setter for accountname.
         * @param  accountname  String value for accountname.
         * @return Builder
         */
        public Builder accountname(String accountname) {
            this.accountname = accountname;
            return this;
        }

        /**
         * Setter for device.
         * @param  device  ResourceDevice value for device.
         * @return Builder
         */
        public Builder device(ResourceDevice device) {
            this.device = device;
            return this;
        }

        /**
         * Setter for resourceidentifier.
         * @param  resourceidentifier  DtoDeviceResourceIdentifier value for resourceidentifier.
         * @return Builder
         */
        public Builder resourceidentifier(DtoDeviceResourceIdentifier resourceidentifier) {
            this.resourceidentifier = resourceidentifier;
            return this;
        }

        /**
         * Builds a new {@link DtoPatchDeviceRequest} object using the set fields.
         * @return {@link DtoPatchDeviceRequest}
         */
        public DtoPatchDeviceRequest build() {
            return new DtoPatchDeviceRequest(accountname, device, resourceidentifier);
        }
    }
}
