/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.verizon.thingspace.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for Geolocation type.
 */
public class Geolocation {
    private double latitude;
    private double longitude;

    /**
     * Default constructor.
     */
    public Geolocation() {
    }

    /**
     * Initialization constructor.
     * @param  latitude  double value for latitude.
     * @param  longitude  double value for longitude.
     */
    public Geolocation(
            double latitude,
            double longitude) {
        this.latitude = latitude;
        this.longitude = longitude;
    }

    /**
     * Getter for Latitude.
     * The GPS Latitude value
     * @return Returns the double
     */
    @JsonGetter("Latitude")
    public double getLatitude() {
        return latitude;
    }

    /**
     * Setter for Latitude.
     * The GPS Latitude value
     * @param latitude Value for double
     */
    @JsonSetter("Latitude")
    public void setLatitude(double latitude) {
        this.latitude = latitude;
    }

    /**
     * Getter for Longitude.
     * The GPS Longitude value
     * @return Returns the double
     */
    @JsonGetter("Longitude")
    public double getLongitude() {
        return longitude;
    }

    /**
     * Setter for Longitude.
     * The GPS Longitude value
     * @param longitude Value for double
     */
    @JsonSetter("Longitude")
    public void setLongitude(double longitude) {
        this.longitude = longitude;
    }

    /**
     * Converts this Geolocation into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Geolocation [" + "latitude=" + latitude + ", longitude=" + longitude + "]";
    }

    /**
     * Builds a new {@link Geolocation.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Geolocation.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(latitude, longitude);
        return builder;
    }

    /**
     * Class to build instances of {@link Geolocation}.
     */
    public static class Builder {
        private double latitude;
        private double longitude;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  latitude  double value for latitude.
         * @param  longitude  double value for longitude.
         */
        public Builder(double latitude, double longitude) {
            this.latitude = latitude;
            this.longitude = longitude;
        }

        /**
         * Setter for latitude.
         * @param  latitude  double value for latitude.
         * @return Builder
         */
        public Builder latitude(double latitude) {
            this.latitude = latitude;
            return this;
        }

        /**
         * Setter for longitude.
         * @param  longitude  double value for longitude.
         * @return Builder
         */
        public Builder longitude(double longitude) {
            this.longitude = longitude;
            return this;
        }

        /**
         * Builds a new {@link Geolocation} object using the set fields.
         * @return {@link Geolocation}
         */
        public Geolocation build() {
            return new Geolocation(latitude, longitude);
        }
    }
}
