/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.verizon.thingspace.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for HplDeviceId type.
 */
public class HplDeviceId {
    private String kind;
    private String id;

    /**
     * Default constructor.
     */
    public HplDeviceId() {
    }

    /**
     * Initialization constructor.
     * @param  kind  String value for kind.
     * @param  id  String value for id.
     */
    public HplDeviceId(
            String kind,
            String id) {
        this.kind = kind;
        this.id = id;
    }

    /**
     * Getter for Kind.
     * The type of ID. This can be IMEI or ICCID.
     * @return Returns the String
     */
    @JsonGetter("kind")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getKind() {
        return kind;
    }

    /**
     * Setter for Kind.
     * The type of ID. This can be IMEI or ICCID.
     * @param kind Value for String
     */
    @JsonSetter("kind")
    public void setKind(String kind) {
        this.kind = kind;
    }

    /**
     * Getter for Id.
     * The ID value.
     * @return Returns the String
     */
    @JsonGetter("id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getId() {
        return id;
    }

    /**
     * Setter for Id.
     * The ID value.
     * @param id Value for String
     */
    @JsonSetter("id")
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Converts this HplDeviceId into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "HplDeviceId [" + "kind=" + kind + ", id=" + id + "]";
    }

    /**
     * Builds a new {@link HplDeviceId.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link HplDeviceId.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .kind(getKind())
                .id(getId());
        return builder;
    }

    /**
     * Class to build instances of {@link HplDeviceId}.
     */
    public static class Builder {
        private String kind;
        private String id;



        /**
         * Setter for kind.
         * @param  kind  String value for kind.
         * @return Builder
         */
        public Builder kind(String kind) {
            this.kind = kind;
            return this;
        }

        /**
         * Setter for id.
         * @param  id  String value for id.
         * @return Builder
         */
        public Builder id(String id) {
            this.id = id;
            return this;
        }

        /**
         * Builds a new {@link HplDeviceId} object using the set fields.
         * @return {@link HplDeviceId}
         */
        public HplDeviceId build() {
            return new HplDeviceId(kind, id);
        }
    }
}
