/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.verizon.thingspace.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for OffsetSystem type.
 */
public class OffsetSystem {
    private Offset offset;

    /**
     * Default constructor.
     */
    public OffsetSystem() {
    }

    /**
     * Initialization constructor.
     * @param  offset  Offset value for offset.
     */
    public OffsetSystem(
            Offset offset) {
        this.offset = offset;
    }

    /**
     * Getter for Offset.
     * The sequence of node offsets then describes a path or polygon in the Lat-Long system.
     * @return Returns the Offset
     */
    @JsonGetter("offset")
    public Offset getOffset() {
        return offset;
    }

    /**
     * Setter for Offset.
     * The sequence of node offsets then describes a path or polygon in the Lat-Long system.
     * @param offset Value for Offset
     */
    @JsonSetter("offset")
    public void setOffset(Offset offset) {
        this.offset = offset;
    }

    /**
     * Converts this OffsetSystem into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "OffsetSystem [" + "offset=" + offset + "]";
    }

    /**
     * Builds a new {@link OffsetSystem.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link OffsetSystem.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(offset);
        return builder;
    }

    /**
     * Class to build instances of {@link OffsetSystem}.
     */
    public static class Builder {
        private Offset offset;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  offset  Offset value for offset.
         */
        public Builder(Offset offset) {
            this.offset = offset;
        }

        /**
         * Setter for offset.
         * @param  offset  Offset value for offset.
         * @return Builder
         */
        public Builder offset(Offset offset) {
            this.offset = offset;
            return this;
        }

        /**
         * Builds a new {@link OffsetSystem} object using the set fields.
         * @return {@link OffsetSystem}
         */
        public OffsetSystem build() {
            return new OffsetSystem(offset);
        }
    }
}
