/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.verizon.thingspace.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for Payload type.
 */
public class Payload {
    private ResourceOnBoardSensor addsensor;

    /**
     * Default constructor.
     */
    public Payload() {
    }

    /**
     * Initialization constructor.
     * @param  addsensor  ResourceOnBoardSensor value for addsensor.
     */
    public Payload(
            ResourceOnBoardSensor addsensor) {
        this.addsensor = addsensor;
    }

    /**
     * Getter for Addsensor.
     * @return Returns the ResourceOnBoardSensor
     */
    @JsonGetter("addsensor")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public ResourceOnBoardSensor getAddsensor() {
        return addsensor;
    }

    /**
     * Setter for Addsensor.
     * @param addsensor Value for ResourceOnBoardSensor
     */
    @JsonSetter("addsensor")
    public void setAddsensor(ResourceOnBoardSensor addsensor) {
        this.addsensor = addsensor;
    }

    /**
     * Converts this Payload into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Payload [" + "addsensor=" + addsensor + "]";
    }

    /**
     * Builds a new {@link Payload.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Payload.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .addsensor(getAddsensor());
        return builder;
    }

    /**
     * Class to build instances of {@link Payload}.
     */
    public static class Builder {
        private ResourceOnBoardSensor addsensor;



        /**
         * Setter for addsensor.
         * @param  addsensor  ResourceOnBoardSensor value for addsensor.
         * @return Builder
         */
        public Builder addsensor(ResourceOnBoardSensor addsensor) {
            this.addsensor = addsensor;
            return this;
        }

        /**
         * Builds a new {@link Payload} object using the set fields.
         * @return {@link Payload}
         */
        public Payload build() {
            return new Payload(addsensor);
        }
    }
}
