/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.verizon.thingspace.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;

/**
 * This is a model class for Polygon type.
 */
public class Polygon {
    private Type3Enum type;
    private List<List<List<Double>>> coordinates;

    /**
     * Default constructor.
     */
    public Polygon() {
    }

    /**
     * Initialization constructor.
     * @param  type  Type3Enum value for type.
     * @param  coordinates  List of Double value for coordinates.
     */
    @JsonCreator
    public Polygon(
            @JsonProperty("type") Type3Enum type,
            @JsonProperty("coordinates") List<List<List<Double>>> coordinates) {
        this.type = type;
        this.coordinates = coordinates;
    }

    /**
     * Getter for Type.
     * @return Returns the Type3Enum
     */
    @JsonGetter("type")
    public Type3Enum getType() {
        return type;
    }

    /**
     * Setter for Type.
     * @param type Value for Type3Enum
     */
    @JsonSetter("type")
    public void setType(Type3Enum type) {
        this.type = type;
    }

    /**
     * Getter for Coordinates.
     * @return Returns the List of Double
     */
    @JsonGetter("coordinates")
    public List<List<List<Double>>> getCoordinates() {
        return coordinates;
    }

    /**
     * Setter for Coordinates.
     * @param coordinates Value for List of Double
     */
    @JsonSetter("coordinates")
    public void setCoordinates(List<List<List<Double>>> coordinates) {
        this.coordinates = coordinates;
    }

    /**
     * Converts this Polygon into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Polygon [" + "type=" + type + ", coordinates=" + coordinates + "]";
    }

    /**
     * Builds a new {@link Polygon.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Polygon.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(type, coordinates);
        return builder;
    }

    /**
     * Class to build instances of {@link Polygon}.
     */
    public static class Builder {
        private Type3Enum type;
        private List<List<List<Double>>> coordinates;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  type  Type3Enum value for type.
         * @param  coordinates  List of Double value for coordinates.
         */
        public Builder(Type3Enum type, List<List<List<Double>>> coordinates) {
            this.type = type;
            this.coordinates = coordinates;
        }

        /**
         * Setter for type.
         * @param  type  Type3Enum value for type.
         * @return Builder
         */
        public Builder type(Type3Enum type) {
            this.type = type;
            return this;
        }

        /**
         * Setter for coordinates.
         * @param  coordinates  List of Double value for coordinates.
         * @return Builder
         */
        public Builder coordinates(List<List<List<Double>>> coordinates) {
            this.coordinates = coordinates;
            return this;
        }

        /**
         * Builds a new {@link Polygon} object using the set fields.
         * @return {@link Polygon}
         */
        public Polygon build() {
            return new Polygon(type, coordinates);
        }
    }
}
