/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.verizon.thingspace.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for PortlandCement type.
 */
public class PortlandCement {
    private Type6Enum type;

    /**
     * Default constructor.
     */
    public PortlandCement() {
        type = Type6Enum.TRAVELED;
    }

    /**
     * Initialization constructor.
     * @param  type  Type6Enum value for type.
     */
    public PortlandCement(
            Type6Enum type) {
        this.type = type;
    }

    /**
     * Getter for Type.
     * Indicates the type of portland cement.
     * @return Returns the Type6Enum
     */
    @JsonGetter("type")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Type6Enum getType() {
        return type;
    }

    /**
     * Setter for Type.
     * Indicates the type of portland cement.
     * @param type Value for Type6Enum
     */
    @JsonSetter("type")
    public void setType(Type6Enum type) {
        this.type = type;
    }

    /**
     * Converts this PortlandCement into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "PortlandCement [" + "type=" + type + "]";
    }

    /**
     * Builds a new {@link PortlandCement.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link PortlandCement.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .type(getType());
        return builder;
    }

    /**
     * Class to build instances of {@link PortlandCement}.
     */
    public static class Builder {
        private Type6Enum type = Type6Enum.TRAVELED;



        /**
         * Setter for type.
         * @param  type  Type6Enum value for type.
         * @return Builder
         */
        public Builder type(Type6Enum type) {
            this.type = type;
            return this;
        }

        /**
         * Builds a new {@link PortlandCement} object using the set fields.
         * @return {@link PortlandCement}
         */
        public PortlandCement build() {
            return new PortlandCement(type);
        }
    }
}
