/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.verizon.thingspace.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for ResourceResourceQuery type.
 */
public class ResourceResourceQuery {
    private Devicepropertyfilter filter;

    /**
     * Default constructor.
     */
    public ResourceResourceQuery() {
    }

    /**
     * Initialization constructor.
     * @param  filter  Devicepropertyfilter value for filter.
     */
    public ResourceResourceQuery(
            Devicepropertyfilter filter) {
        this.filter = filter;
    }

    /**
     * Getter for Filter.
     * @return Returns the Devicepropertyfilter
     */
    @JsonGetter("filter")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Devicepropertyfilter getFilter() {
        return filter;
    }

    /**
     * Setter for Filter.
     * @param filter Value for Devicepropertyfilter
     */
    @JsonSetter("filter")
    public void setFilter(Devicepropertyfilter filter) {
        this.filter = filter;
    }

    /**
     * Converts this ResourceResourceQuery into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ResourceResourceQuery [" + "filter=" + filter + "]";
    }

    /**
     * Builds a new {@link ResourceResourceQuery.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ResourceResourceQuery.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .filter(getFilter());
        return builder;
    }

    /**
     * Class to build instances of {@link ResourceResourceQuery}.
     */
    public static class Builder {
        private Devicepropertyfilter filter;



        /**
         * Setter for filter.
         * @param  filter  Devicepropertyfilter value for filter.
         * @return Builder
         */
        public Builder filter(Devicepropertyfilter filter) {
            this.filter = filter;
            return this;
        }

        /**
         * Builds a new {@link ResourceResourceQuery} object using the set fields.
         * @return {@link ResourceResourceQuery}
         */
        public ResourceResourceQuery build() {
            return new ResourceResourceQuery(filter);
        }
    }
}
