/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.verizon.thingspace.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for Snow type.
 */
public class Snow {
    private Type13Enum type;

    /**
     * Default constructor.
     */
    public Snow() {
    }

    /**
     * Initialization constructor.
     * @param  type  Type13Enum value for type.
     */
    public Snow(
            Type13Enum type) {
        this.type = type;
    }

    /**
     * Getter for Type.
     * Indicates the type of snow.
     * @return Returns the Type13Enum
     */
    @JsonGetter("type")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Type13Enum getType() {
        return type;
    }

    /**
     * Setter for Type.
     * Indicates the type of snow.
     * @param type Value for Type13Enum
     */
    @JsonSetter("type")
    public void setType(Type13Enum type) {
        this.type = type;
    }

    /**
     * Converts this Snow into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Snow [" + "type=" + type + "]";
    }

    /**
     * Builds a new {@link Snow.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Snow.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .type(getType());
        return builder;
    }

    /**
     * Class to build instances of {@link Snow}.
     */
    public static class Builder {
        private Type13Enum type;



        /**
         * Setter for type.
         * @param  type  Type13Enum value for type.
         * @return Builder
         */
        public Builder type(Type13Enum type) {
            this.type = type;
            return this;
        }

        /**
         * Builds a new {@link Snow} object using the set fields.
         * @return {@link Snow}
         */
        public Snow build() {
            return new Snow(type);
        }
    }
}
