/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.verizon.thingspace.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for Speed type.
 */
public class Speed {
    private double min;
    private double max;

    /**
     * Default constructor.
     */
    public Speed() {
    }

    /**
     * Initialization constructor.
     * @param  min  double value for min.
     * @param  max  double value for max.
     */
    public Speed(
            double min,
            double max) {
        this.min = min;
        this.max = max;
    }

    /**
     * Getter for Min.
     * The minimum required speed in m/s.
     * @return Returns the double
     */
    @JsonGetter("min")
    public double getMin() {
        return min;
    }

    /**
     * Setter for Min.
     * The minimum required speed in m/s.
     * @param min Value for double
     */
    @JsonSetter("min")
    public void setMin(double min) {
        this.min = min;
    }

    /**
     * Getter for Max.
     * The maximum acceptable speed in m/s
     * @return Returns the double
     */
    @JsonGetter("max")
    public double getMax() {
        return max;
    }

    /**
     * Setter for Max.
     * The maximum acceptable speed in m/s
     * @param max Value for double
     */
    @JsonSetter("max")
    public void setMax(double max) {
        this.max = max;
    }

    /**
     * Converts this Speed into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "Speed [" + "min=" + min + ", max=" + max + "]";
    }

    /**
     * Builds a new {@link Speed.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link Speed.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(min, max);
        return builder;
    }

    /**
     * Class to build instances of {@link Speed}.
     */
    public static class Builder {
        private double min;
        private double max;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  min  double value for min.
         * @param  max  double value for max.
         */
        public Builder(double min, double max) {
            this.min = min;
            this.max = max;
        }

        /**
         * Setter for min.
         * @param  min  double value for min.
         * @return Builder
         */
        public Builder min(double min) {
            this.min = min;
            return this;
        }

        /**
         * Setter for max.
         * @param  max  double value for max.
         * @return Builder
         */
        public Builder max(double max) {
            this.max = max;
            return this;
        }

        /**
         * Builds a new {@link Speed} object using the set fields.
         * @return {@link Speed}
         */
        public Speed build() {
            return new Speed(min, max);
        }
    }
}
