/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.verizon.m5gedge.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for AccountGroupShare type.
 */
public class AccountGroupShare {
    private AccountGroupShareIndividual accountGroupShareIndividual;

    /**
     * Default constructor.
     */
    public AccountGroupShare() {
    }

    /**
     * Initialization constructor.
     * @param  accountGroupShareIndividual  AccountGroupShareIndividual value for
     *         accountGroupShareIndividual.
     */
    public AccountGroupShare(
            AccountGroupShareIndividual accountGroupShareIndividual) {
        this.accountGroupShareIndividual = accountGroupShareIndividual;
    }

    /**
     * Getter for AccountGroupShareIndividual.
     * @return Returns the AccountGroupShareIndividual
     */
    @JsonGetter("accountGroupShareIndividual")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public AccountGroupShareIndividual getAccountGroupShareIndividual() {
        return accountGroupShareIndividual;
    }

    /**
     * Setter for AccountGroupShareIndividual.
     * @param accountGroupShareIndividual Value for AccountGroupShareIndividual
     */
    @JsonSetter("accountGroupShareIndividual")
    public void setAccountGroupShareIndividual(AccountGroupShareIndividual accountGroupShareIndividual) {
        this.accountGroupShareIndividual = accountGroupShareIndividual;
    }

    /**
     * Converts this AccountGroupShare into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "AccountGroupShare [" + "accountGroupShareIndividual=" + accountGroupShareIndividual
                + "]";
    }

    /**
     * Builds a new {@link AccountGroupShare.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link AccountGroupShare.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .accountGroupShareIndividual(getAccountGroupShareIndividual());
        return builder;
    }

    /**
     * Class to build instances of {@link AccountGroupShare}.
     */
    public static class Builder {
        private AccountGroupShareIndividual accountGroupShareIndividual;



        /**
         * Setter for accountGroupShareIndividual.
         * @param  accountGroupShareIndividual  AccountGroupShareIndividual value for
         *         accountGroupShareIndividual.
         * @return Builder
         */
        public Builder accountGroupShareIndividual(
                AccountGroupShareIndividual accountGroupShareIndividual) {
            this.accountGroupShareIndividual = accountGroupShareIndividual;
            return this;
        }

        /**
         * Builds a new {@link AccountGroupShare} object using the set fields.
         * @return {@link AccountGroupShare}
         */
        public AccountGroupShare build() {
            return new AccountGroupShare(accountGroupShareIndividual);
        }
    }
}
