/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.verizon.m5gedge.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;

/**
 * This is a model class for DeviceProfileRequest type.
 */
public class DeviceProfileRequest {
    private List<GIODeviceList> devices;
    private String accountName;
    private String servicePlan;

    /**
     * Default constructor.
     */
    public DeviceProfileRequest() {
    }

    /**
     * Initialization constructor.
     * @param  devices  List of GIODeviceList value for devices.
     * @param  accountName  String value for accountName.
     * @param  servicePlan  String value for servicePlan.
     */
    public DeviceProfileRequest(
            List<GIODeviceList> devices,
            String accountName,
            String servicePlan) {
        this.devices = devices;
        this.accountName = accountName;
        this.servicePlan = servicePlan;
    }

    /**
     * Getter for Devices.
     * @return Returns the List of GIODeviceList
     */
    @JsonGetter("devices")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<GIODeviceList> getDevices() {
        return devices;
    }

    /**
     * Setter for Devices.
     * @param devices Value for List of GIODeviceList
     */
    @JsonSetter("devices")
    public void setDevices(List<GIODeviceList> devices) {
        this.devices = devices;
    }

    /**
     * Getter for AccountName.
     * @return Returns the String
     */
    @JsonGetter("accountName")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getAccountName() {
        return accountName;
    }

    /**
     * Setter for AccountName.
     * @param accountName Value for String
     */
    @JsonSetter("accountName")
    public void setAccountName(String accountName) {
        this.accountName = accountName;
    }

    /**
     * Getter for ServicePlan.
     * @return Returns the String
     */
    @JsonGetter("servicePlan")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getServicePlan() {
        return servicePlan;
    }

    /**
     * Setter for ServicePlan.
     * @param servicePlan Value for String
     */
    @JsonSetter("servicePlan")
    public void setServicePlan(String servicePlan) {
        this.servicePlan = servicePlan;
    }

    /**
     * Converts this DeviceProfileRequest into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "DeviceProfileRequest [" + "devices=" + devices + ", accountName=" + accountName
                + ", servicePlan=" + servicePlan + "]";
    }

    /**
     * Builds a new {@link DeviceProfileRequest.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link DeviceProfileRequest.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .devices(getDevices())
                .accountName(getAccountName())
                .servicePlan(getServicePlan());
        return builder;
    }

    /**
     * Class to build instances of {@link DeviceProfileRequest}.
     */
    public static class Builder {
        private List<GIODeviceList> devices;
        private String accountName;
        private String servicePlan;



        /**
         * Setter for devices.
         * @param  devices  List of GIODeviceList value for devices.
         * @return Builder
         */
        public Builder devices(List<GIODeviceList> devices) {
            this.devices = devices;
            return this;
        }

        /**
         * Setter for accountName.
         * @param  accountName  String value for accountName.
         * @return Builder
         */
        public Builder accountName(String accountName) {
            this.accountName = accountName;
            return this;
        }

        /**
         * Setter for servicePlan.
         * @param  servicePlan  String value for servicePlan.
         * @return Builder
         */
        public Builder servicePlan(String servicePlan) {
            this.servicePlan = servicePlan;
            return this;
        }

        /**
         * Builds a new {@link DeviceProfileRequest} object using the set fields.
         * @return {@link DeviceProfileRequest}
         */
        public DeviceProfileRequest build() {
            return new DeviceProfileRequest(devices, accountName, servicePlan);
        }
    }
}
