/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.verizon.m5gedge.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for EdgeDiscoveryResultData type.
 */
public class EdgeDiscoveryResultData {
    private String additionalMessage;

    /**
     * Default constructor.
     */
    public EdgeDiscoveryResultData() {
    }

    /**
     * Initialization constructor.
     * @param  additionalMessage  String value for additionalMessage.
     */
    public EdgeDiscoveryResultData(
            String additionalMessage) {
        this.additionalMessage = additionalMessage;
    }

    /**
     * Getter for AdditionalMessage.
     * @return Returns the String
     */
    @JsonGetter("additionalMessage")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getAdditionalMessage() {
        return additionalMessage;
    }

    /**
     * Setter for AdditionalMessage.
     * @param additionalMessage Value for String
     */
    @JsonSetter("additionalMessage")
    public void setAdditionalMessage(String additionalMessage) {
        this.additionalMessage = additionalMessage;
    }

    /**
     * Converts this EdgeDiscoveryResultData into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "EdgeDiscoveryResultData [" + "additionalMessage=" + additionalMessage + "]";
    }

    /**
     * Builds a new {@link EdgeDiscoveryResultData.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link EdgeDiscoveryResultData.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .additionalMessage(getAdditionalMessage());
        return builder;
    }

    /**
     * Class to build instances of {@link EdgeDiscoveryResultData}.
     */
    public static class Builder {
        private String additionalMessage;



        /**
         * Setter for additionalMessage.
         * @param  additionalMessage  String value for additionalMessage.
         * @return Builder
         */
        public Builder additionalMessage(String additionalMessage) {
            this.additionalMessage = additionalMessage;
            return this;
        }

        /**
         * Builds a new {@link EdgeDiscoveryResultData} object using the set fields.
         * @return {@link EdgeDiscoveryResultData}
         */
        public EdgeDiscoveryResultData build() {
            return new EdgeDiscoveryResultData(additionalMessage);
        }
    }
}
