/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.verizon.m5gedge.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for ExtendedAttributes type.
 */
public class ExtendedAttributes {
    private String key;
    private String value;

    /**
     * Default constructor.
     */
    public ExtendedAttributes() {
    }

    /**
     * Initialization constructor.
     * @param  key  String value for key.
     * @param  value  String value for value.
     */
    public ExtendedAttributes(
            String key,
            String value) {
        this.key = key;
        this.value = value;
    }

    /**
     * Getter for Key.
     * @return Returns the String
     */
    @JsonGetter("key")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getKey() {
        return key;
    }

    /**
     * Setter for Key.
     * @param key Value for String
     */
    @JsonSetter("key")
    public void setKey(String key) {
        this.key = key;
    }

    /**
     * Getter for Value.
     * @return Returns the String
     */
    @JsonGetter("value")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getValue() {
        return value;
    }

    /**
     * Setter for Value.
     * @param value Value for String
     */
    @JsonSetter("value")
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Converts this ExtendedAttributes into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ExtendedAttributes [" + "key=" + key + ", value=" + value + "]";
    }

    /**
     * Builds a new {@link ExtendedAttributes.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ExtendedAttributes.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .key(getKey())
                .value(getValue());
        return builder;
    }

    /**
     * Class to build instances of {@link ExtendedAttributes}.
     */
    public static class Builder {
        private String key;
        private String value;



        /**
         * Setter for key.
         * @param  key  String value for key.
         * @return Builder
         */
        public Builder key(String key) {
            this.key = key;
            return this;
        }

        /**
         * Setter for value.
         * @param  value  String value for value.
         * @return Builder
         */
        public Builder value(String value) {
            this.value = value;
            return this;
        }

        /**
         * Builds a new {@link ExtendedAttributes} object using the set fields.
         * @return {@link ExtendedAttributes}
         */
        public ExtendedAttributes build() {
            return new ExtendedAttributes(key, value);
        }
    }
}
