/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.verizon.m5gedge.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;

/**
 * This is a model class for M5gBichangeRequest type.
 */
public class M5gBichangeRequest {
    private String accountName;
    private String servicePlan;
    private List<DeviceListWithServiceAddress> deviceListWithServiceAddress;
    private String currentServicePlan;

    /**
     * Default constructor.
     */
    public M5gBichangeRequest() {
    }

    /**
     * Initialization constructor.
     * @param  accountName  String value for accountName.
     * @param  servicePlan  String value for servicePlan.
     * @param  deviceListWithServiceAddress  List of DeviceListWithServiceAddress value for
     *         deviceListWithServiceAddress.
     * @param  currentServicePlan  String value for currentServicePlan.
     */
    public M5gBichangeRequest(
            String accountName,
            String servicePlan,
            List<DeviceListWithServiceAddress> deviceListWithServiceAddress,
            String currentServicePlan) {
        this.accountName = accountName;
        this.servicePlan = servicePlan;
        this.deviceListWithServiceAddress = deviceListWithServiceAddress;
        this.currentServicePlan = currentServicePlan;
    }

    /**
     * Getter for AccountName.
     * @return Returns the String
     */
    @JsonGetter("accountName")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getAccountName() {
        return accountName;
    }

    /**
     * Setter for AccountName.
     * @param accountName Value for String
     */
    @JsonSetter("accountName")
    public void setAccountName(String accountName) {
        this.accountName = accountName;
    }

    /**
     * Getter for ServicePlan.
     * @return Returns the String
     */
    @JsonGetter("servicePlan")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getServicePlan() {
        return servicePlan;
    }

    /**
     * Setter for ServicePlan.
     * @param servicePlan Value for String
     */
    @JsonSetter("servicePlan")
    public void setServicePlan(String servicePlan) {
        this.servicePlan = servicePlan;
    }

    /**
     * Getter for DeviceListWithServiceAddress.
     * @return Returns the List of DeviceListWithServiceAddress
     */
    @JsonGetter("deviceListWithServiceAddress")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<DeviceListWithServiceAddress> getDeviceListWithServiceAddress() {
        return deviceListWithServiceAddress;
    }

    /**
     * Setter for DeviceListWithServiceAddress.
     * @param deviceListWithServiceAddress Value for List of DeviceListWithServiceAddress
     */
    @JsonSetter("deviceListWithServiceAddress")
    public void setDeviceListWithServiceAddress(List<DeviceListWithServiceAddress> deviceListWithServiceAddress) {
        this.deviceListWithServiceAddress = deviceListWithServiceAddress;
    }

    /**
     * Getter for CurrentServicePlan.
     * @return Returns the String
     */
    @JsonGetter("currentServicePlan")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getCurrentServicePlan() {
        return currentServicePlan;
    }

    /**
     * Setter for CurrentServicePlan.
     * @param currentServicePlan Value for String
     */
    @JsonSetter("currentServicePlan")
    public void setCurrentServicePlan(String currentServicePlan) {
        this.currentServicePlan = currentServicePlan;
    }

    /**
     * Converts this M5gBichangeRequest into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "M5gBichangeRequest [" + "accountName=" + accountName + ", servicePlan="
                + servicePlan + ", deviceListWithServiceAddress=" + deviceListWithServiceAddress
                + ", currentServicePlan=" + currentServicePlan + "]";
    }

    /**
     * Builds a new {@link M5gBichangeRequest.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link M5gBichangeRequest.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .accountName(getAccountName())
                .servicePlan(getServicePlan())
                .deviceListWithServiceAddress(getDeviceListWithServiceAddress())
                .currentServicePlan(getCurrentServicePlan());
        return builder;
    }

    /**
     * Class to build instances of {@link M5gBichangeRequest}.
     */
    public static class Builder {
        private String accountName;
        private String servicePlan;
        private List<DeviceListWithServiceAddress> deviceListWithServiceAddress;
        private String currentServicePlan;



        /**
         * Setter for accountName.
         * @param  accountName  String value for accountName.
         * @return Builder
         */
        public Builder accountName(String accountName) {
            this.accountName = accountName;
            return this;
        }

        /**
         * Setter for servicePlan.
         * @param  servicePlan  String value for servicePlan.
         * @return Builder
         */
        public Builder servicePlan(String servicePlan) {
            this.servicePlan = servicePlan;
            return this;
        }

        /**
         * Setter for deviceListWithServiceAddress.
         * @param  deviceListWithServiceAddress  List of DeviceListWithServiceAddress value for
         *         deviceListWithServiceAddress.
         * @return Builder
         */
        public Builder deviceListWithServiceAddress(
                List<DeviceListWithServiceAddress> deviceListWithServiceAddress) {
            this.deviceListWithServiceAddress = deviceListWithServiceAddress;
            return this;
        }

        /**
         * Setter for currentServicePlan.
         * @param  currentServicePlan  String value for currentServicePlan.
         * @return Builder
         */
        public Builder currentServicePlan(String currentServicePlan) {
            this.currentServicePlan = currentServicePlan;
            return this;
        }

        /**
         * Builds a new {@link M5gBichangeRequest} object using the set fields.
         * @return {@link M5gBichangeRequest}
         */
        public M5gBichangeRequest build() {
            return new M5gBichangeRequest(accountName, servicePlan, deviceListWithServiceAddress,
                    currentServicePlan);
        }
    }
}
