/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.verizon.m5gedge.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;

/**
 * This is a model class for M5gBiactivateRequest type.
 */
public class M5gBiactivateRequest {
    private String accountName;
    private String servicePlan;
    private List<DeviceListWithServiceAddress1> deviceListWithServiceAddress;
    private String publicIpRestriction;
    private String carrierName;
    private String mdnZipCode;

    /**
     * Default constructor.
     */
    public M5gBiactivateRequest() {
    }

    /**
     * Initialization constructor.
     * @param  accountName  String value for accountName.
     * @param  servicePlan  String value for servicePlan.
     * @param  deviceListWithServiceAddress  List of DeviceListWithServiceAddress1 value for
     *         deviceListWithServiceAddress.
     * @param  publicIpRestriction  String value for publicIpRestriction.
     * @param  carrierName  String value for carrierName.
     * @param  mdnZipCode  String value for mdnZipCode.
     */
    public M5gBiactivateRequest(
            String accountName,
            String servicePlan,
            List<DeviceListWithServiceAddress1> deviceListWithServiceAddress,
            String publicIpRestriction,
            String carrierName,
            String mdnZipCode) {
        this.accountName = accountName;
        this.servicePlan = servicePlan;
        this.deviceListWithServiceAddress = deviceListWithServiceAddress;
        this.publicIpRestriction = publicIpRestriction;
        this.carrierName = carrierName;
        this.mdnZipCode = mdnZipCode;
    }

    /**
     * Getter for AccountName.
     * @return Returns the String
     */
    @JsonGetter("accountName")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getAccountName() {
        return accountName;
    }

    /**
     * Setter for AccountName.
     * @param accountName Value for String
     */
    @JsonSetter("accountName")
    public void setAccountName(String accountName) {
        this.accountName = accountName;
    }

    /**
     * Getter for ServicePlan.
     * @return Returns the String
     */
    @JsonGetter("servicePlan")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getServicePlan() {
        return servicePlan;
    }

    /**
     * Setter for ServicePlan.
     * @param servicePlan Value for String
     */
    @JsonSetter("servicePlan")
    public void setServicePlan(String servicePlan) {
        this.servicePlan = servicePlan;
    }

    /**
     * Getter for DeviceListWithServiceAddress.
     * @return Returns the List of DeviceListWithServiceAddress1
     */
    @JsonGetter("deviceListWithServiceAddress")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<DeviceListWithServiceAddress1> getDeviceListWithServiceAddress() {
        return deviceListWithServiceAddress;
    }

    /**
     * Setter for DeviceListWithServiceAddress.
     * @param deviceListWithServiceAddress Value for List of DeviceListWithServiceAddress1
     */
    @JsonSetter("deviceListWithServiceAddress")
    public void setDeviceListWithServiceAddress(List<DeviceListWithServiceAddress1> deviceListWithServiceAddress) {
        this.deviceListWithServiceAddress = deviceListWithServiceAddress;
    }

    /**
     * Getter for PublicIpRestriction.
     * @return Returns the String
     */
    @JsonGetter("publicIpRestriction")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getPublicIpRestriction() {
        return publicIpRestriction;
    }

    /**
     * Setter for PublicIpRestriction.
     * @param publicIpRestriction Value for String
     */
    @JsonSetter("publicIpRestriction")
    public void setPublicIpRestriction(String publicIpRestriction) {
        this.publicIpRestriction = publicIpRestriction;
    }

    /**
     * Getter for CarrierName.
     * @return Returns the String
     */
    @JsonGetter("carrierName")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getCarrierName() {
        return carrierName;
    }

    /**
     * Setter for CarrierName.
     * @param carrierName Value for String
     */
    @JsonSetter("carrierName")
    public void setCarrierName(String carrierName) {
        this.carrierName = carrierName;
    }

    /**
     * Getter for MdnZipCode.
     * @return Returns the String
     */
    @JsonGetter("mdnZipCode")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getMdnZipCode() {
        return mdnZipCode;
    }

    /**
     * Setter for MdnZipCode.
     * @param mdnZipCode Value for String
     */
    @JsonSetter("mdnZipCode")
    public void setMdnZipCode(String mdnZipCode) {
        this.mdnZipCode = mdnZipCode;
    }

    /**
     * Converts this M5gBiactivateRequest into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "M5gBiactivateRequest [" + "accountName=" + accountName + ", servicePlan="
                + servicePlan + ", deviceListWithServiceAddress=" + deviceListWithServiceAddress
                + ", publicIpRestriction=" + publicIpRestriction + ", carrierName=" + carrierName
                + ", mdnZipCode=" + mdnZipCode + "]";
    }

    /**
     * Builds a new {@link M5gBiactivateRequest.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link M5gBiactivateRequest.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .accountName(getAccountName())
                .servicePlan(getServicePlan())
                .deviceListWithServiceAddress(getDeviceListWithServiceAddress())
                .publicIpRestriction(getPublicIpRestriction())
                .carrierName(getCarrierName())
                .mdnZipCode(getMdnZipCode());
        return builder;
    }

    /**
     * Class to build instances of {@link M5gBiactivateRequest}.
     */
    public static class Builder {
        private String accountName;
        private String servicePlan;
        private List<DeviceListWithServiceAddress1> deviceListWithServiceAddress;
        private String publicIpRestriction;
        private String carrierName;
        private String mdnZipCode;



        /**
         * Setter for accountName.
         * @param  accountName  String value for accountName.
         * @return Builder
         */
        public Builder accountName(String accountName) {
            this.accountName = accountName;
            return this;
        }

        /**
         * Setter for servicePlan.
         * @param  servicePlan  String value for servicePlan.
         * @return Builder
         */
        public Builder servicePlan(String servicePlan) {
            this.servicePlan = servicePlan;
            return this;
        }

        /**
         * Setter for deviceListWithServiceAddress.
         * @param  deviceListWithServiceAddress  List of DeviceListWithServiceAddress1 value for
         *         deviceListWithServiceAddress.
         * @return Builder
         */
        public Builder deviceListWithServiceAddress(
                List<DeviceListWithServiceAddress1> deviceListWithServiceAddress) {
            this.deviceListWithServiceAddress = deviceListWithServiceAddress;
            return this;
        }

        /**
         * Setter for publicIpRestriction.
         * @param  publicIpRestriction  String value for publicIpRestriction.
         * @return Builder
         */
        public Builder publicIpRestriction(String publicIpRestriction) {
            this.publicIpRestriction = publicIpRestriction;
            return this;
        }

        /**
         * Setter for carrierName.
         * @param  carrierName  String value for carrierName.
         * @return Builder
         */
        public Builder carrierName(String carrierName) {
            this.carrierName = carrierName;
            return this;
        }

        /**
         * Setter for mdnZipCode.
         * @param  mdnZipCode  String value for mdnZipCode.
         * @return Builder
         */
        public Builder mdnZipCode(String mdnZipCode) {
            this.mdnZipCode = mdnZipCode;
            return this;
        }

        /**
         * Builds a new {@link M5gBiactivateRequest} object using the set fields.
         * @return {@link M5gBiactivateRequest}
         */
        public M5gBiactivateRequest build() {
            return new M5gBiactivateRequest(accountName, servicePlan, deviceListWithServiceAddress,
                    publicIpRestriction, carrierName, mdnZipCode);
        }
    }
}
