/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.verizon.m5gedge.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for ManagedAccAddedList type.
 */
public class ManagedAccAddedList {
    private String id;
    private String txid;

    /**
     * Default constructor.
     */
    public ManagedAccAddedList() {
    }

    /**
     * Initialization constructor.
     * @param  id  String value for id.
     * @param  txid  String value for txid.
     */
    public ManagedAccAddedList(
            String id,
            String txid) {
        this.id = id;
        this.txid = txid;
    }

    /**
     * Getter for Id.
     * Account name
     * @return Returns the String
     */
    @JsonGetter("id")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getId() {
        return id;
    }

    /**
     * Setter for Id.
     * Account name
     * @param id Value for String
     */
    @JsonSetter("id")
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Getter for Txid.
     * Transaction identifier
     * @return Returns the String
     */
    @JsonGetter("txid")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getTxid() {
        return txid;
    }

    /**
     * Setter for Txid.
     * Transaction identifier
     * @param txid Value for String
     */
    @JsonSetter("txid")
    public void setTxid(String txid) {
        this.txid = txid;
    }

    /**
     * Converts this ManagedAccAddedList into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ManagedAccAddedList [" + "id=" + id + ", txid=" + txid + "]";
    }

    /**
     * Builds a new {@link ManagedAccAddedList.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ManagedAccAddedList.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .id(getId())
                .txid(getTxid());
        return builder;
    }

    /**
     * Class to build instances of {@link ManagedAccAddedList}.
     */
    public static class Builder {
        private String id;
        private String txid;



        /**
         * Setter for id.
         * @param  id  String value for id.
         * @return Builder
         */
        public Builder id(String id) {
            this.id = id;
            return this;
        }

        /**
         * Setter for txid.
         * @param  txid  String value for txid.
         * @return Builder
         */
        public Builder txid(String txid) {
            this.txid = txid;
            return this;
        }

        /**
         * Builds a new {@link ManagedAccAddedList} object using the set fields.
         * @return {@link ManagedAccAddedList}
         */
        public ManagedAccAddedList build() {
            return new ManagedAccAddedList(id, txid);
        }
    }
}
