/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.verizon.m5gedge.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for ManagedAccountsProvisionResponse type.
 */
public class ManagedAccountsProvisionResponse {
    private String txid;
    private String accountName;
    private String paccountName;
    private ServiceNameEnum serviceName;
    private String status;
    private String reason;

    /**
     * Default constructor.
     */
    public ManagedAccountsProvisionResponse() {
        serviceName = ServiceNameEnum.LOCATION;
    }

    /**
     * Initialization constructor.
     * @param  txid  String value for txid.
     * @param  accountName  String value for accountName.
     * @param  paccountName  String value for paccountName.
     * @param  serviceName  ServiceNameEnum value for serviceName.
     * @param  status  String value for status.
     * @param  reason  String value for reason.
     */
    public ManagedAccountsProvisionResponse(
            String txid,
            String accountName,
            String paccountName,
            ServiceNameEnum serviceName,
            String status,
            String reason) {
        this.txid = txid;
        this.accountName = accountName;
        this.paccountName = paccountName;
        this.serviceName = serviceName;
        this.status = status;
        this.reason = reason;
    }

    /**
     * Getter for Txid.
     * Transaction identifier
     * @return Returns the String
     */
    @JsonGetter("txid")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getTxid() {
        return txid;
    }

    /**
     * Setter for Txid.
     * Transaction identifier
     * @param txid Value for String
     */
    @JsonSetter("txid")
    public void setTxid(String txid) {
        this.txid = txid;
    }

    /**
     * Getter for AccountName.
     * Account identifier
     * @return Returns the String
     */
    @JsonGetter("accountName")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getAccountName() {
        return accountName;
    }

    /**
     * Setter for AccountName.
     * Account identifier
     * @param accountName Value for String
     */
    @JsonSetter("accountName")
    public void setAccountName(String accountName) {
        this.accountName = accountName;
    }

    /**
     * Getter for PaccountName.
     * Primary Account identifier
     * @return Returns the String
     */
    @JsonGetter("paccountName")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getPaccountName() {
        return paccountName;
    }

    /**
     * Setter for PaccountName.
     * Primary Account identifier
     * @param paccountName Value for String
     */
    @JsonSetter("paccountName")
    public void setPaccountName(String paccountName) {
        this.paccountName = paccountName;
    }

    /**
     * Getter for ServiceName.
     * Service name
     * @return Returns the ServiceNameEnum
     */
    @JsonGetter("serviceName")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public ServiceNameEnum getServiceName() {
        return serviceName;
    }

    /**
     * Setter for ServiceName.
     * Service name
     * @param serviceName Value for ServiceNameEnum
     */
    @JsonSetter("serviceName")
    public void setServiceName(ServiceNameEnum serviceName) {
        this.serviceName = serviceName;
    }

    /**
     * Getter for Status.
     * Provision status. Success or Fail
     * @return Returns the String
     */
    @JsonGetter("status")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getStatus() {
        return status;
    }

    /**
     * Setter for Status.
     * Provision status. Success or Fail
     * @param status Value for String
     */
    @JsonSetter("status")
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * Getter for Reason.
     * Detailed reason
     * @return Returns the String
     */
    @JsonGetter("reason")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getReason() {
        return reason;
    }

    /**
     * Setter for Reason.
     * Detailed reason
     * @param reason Value for String
     */
    @JsonSetter("reason")
    public void setReason(String reason) {
        this.reason = reason;
    }

    /**
     * Converts this ManagedAccountsProvisionResponse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ManagedAccountsProvisionResponse [" + "txid=" + txid + ", accountName="
                + accountName + ", paccountName=" + paccountName + ", serviceName=" + serviceName
                + ", status=" + status + ", reason=" + reason + "]";
    }

    /**
     * Builds a new {@link ManagedAccountsProvisionResponse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ManagedAccountsProvisionResponse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .txid(getTxid())
                .accountName(getAccountName())
                .paccountName(getPaccountName())
                .serviceName(getServiceName())
                .status(getStatus())
                .reason(getReason());
        return builder;
    }

    /**
     * Class to build instances of {@link ManagedAccountsProvisionResponse}.
     */
    public static class Builder {
        private String txid;
        private String accountName;
        private String paccountName;
        private ServiceNameEnum serviceName = ServiceNameEnum.LOCATION;
        private String status;
        private String reason;



        /**
         * Setter for txid.
         * @param  txid  String value for txid.
         * @return Builder
         */
        public Builder txid(String txid) {
            this.txid = txid;
            return this;
        }

        /**
         * Setter for accountName.
         * @param  accountName  String value for accountName.
         * @return Builder
         */
        public Builder accountName(String accountName) {
            this.accountName = accountName;
            return this;
        }

        /**
         * Setter for paccountName.
         * @param  paccountName  String value for paccountName.
         * @return Builder
         */
        public Builder paccountName(String paccountName) {
            this.paccountName = paccountName;
            return this;
        }

        /**
         * Setter for serviceName.
         * @param  serviceName  ServiceNameEnum value for serviceName.
         * @return Builder
         */
        public Builder serviceName(ServiceNameEnum serviceName) {
            this.serviceName = serviceName;
            return this;
        }

        /**
         * Setter for status.
         * @param  status  String value for status.
         * @return Builder
         */
        public Builder status(String status) {
            this.status = status;
            return this;
        }

        /**
         * Setter for reason.
         * @param  reason  String value for reason.
         * @return Builder
         */
        public Builder reason(String reason) {
            this.reason = reason;
            return this;
        }

        /**
         * Builds a new {@link ManagedAccountsProvisionResponse} object using the set fields.
         * @return {@link ManagedAccountsProvisionResponse}
         */
        public ManagedAccountsProvisionResponse build() {
            return new ManagedAccountsProvisionResponse(txid, accountName, paccountName,
                    serviceName, status, reason);
        }
    }
}
