/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.verizon.m5gedge.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for PlaceOfUse type.
 */
public class PlaceOfUse {
    private Address address;
    private CustomerName customerName;

    /**
     * Default constructor.
     */
    public PlaceOfUse() {
    }

    /**
     * Initialization constructor.
     * @param  address  Address value for address.
     * @param  customerName  CustomerName value for customerName.
     */
    public PlaceOfUse(
            Address address,
            CustomerName customerName) {
        this.address = address;
        this.customerName = customerName;
    }

    /**
     * Getter for Address.
     * The customer address for the line's primary place of use, for line usage taxation.
     * @return Returns the Address
     */
    @JsonGetter("address")
    public Address getAddress() {
        return address;
    }

    /**
     * Setter for Address.
     * The customer address for the line's primary place of use, for line usage taxation.
     * @param address Value for Address
     */
    @JsonSetter("address")
    public void setAddress(Address address) {
        this.address = address;
    }

    /**
     * Getter for CustomerName.
     * The customer name to be used for line usage taxation.
     * @return Returns the CustomerName
     */
    @JsonGetter("customerName")
    public CustomerName getCustomerName() {
        return customerName;
    }

    /**
     * Setter for CustomerName.
     * The customer name to be used for line usage taxation.
     * @param customerName Value for CustomerName
     */
    @JsonSetter("customerName")
    public void setCustomerName(CustomerName customerName) {
        this.customerName = customerName;
    }

    /**
     * Converts this PlaceOfUse into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "PlaceOfUse [" + "address=" + address + ", customerName=" + customerName + "]";
    }

    /**
     * Builds a new {@link PlaceOfUse.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link PlaceOfUse.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(address, customerName);
        return builder;
    }

    /**
     * Class to build instances of {@link PlaceOfUse}.
     */
    public static class Builder {
        private Address address;
        private CustomerName customerName;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  address  Address value for address.
         * @param  customerName  CustomerName value for customerName.
         */
        public Builder(Address address, CustomerName customerName) {
            this.address = address;
            this.customerName = customerName;
        }

        /**
         * Setter for address.
         * @param  address  Address value for address.
         * @return Builder
         */
        public Builder address(Address address) {
            this.address = address;
            return this;
        }

        /**
         * Setter for customerName.
         * @param  customerName  CustomerName value for customerName.
         * @return Builder
         */
        public Builder customerName(CustomerName customerName) {
            this.customerName = customerName;
            return this;
        }

        /**
         * Builds a new {@link PlaceOfUse} object using the set fields.
         * @return {@link PlaceOfUse}
         */
        public PlaceOfUse build() {
            return new PlaceOfUse(address, customerName);
        }
    }
}
