/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.verizon.m5gedge.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for RegisteredCallbacks type.
 */
public class RegisteredCallbacks {
    private String aname;
    private String name;
    private String url;
    private String username;
    private String password;

    /**
     * Default constructor.
     */
    public RegisteredCallbacks() {
    }

    /**
     * Initialization constructor.
     * @param  aname  String value for aname.
     * @param  name  String value for name.
     * @param  url  String value for url.
     * @param  username  String value for username.
     * @param  password  String value for password.
     */
    public RegisteredCallbacks(
            String aname,
            String name,
            String url,
            String username,
            String password) {
        this.aname = aname;
        this.name = name;
        this.url = url;
        this.username = username;
        this.password = password;
    }

    /**
     * Getter for Aname.
     * The name of the billing account for which callback messages will be sent.
     * @return Returns the String
     */
    @JsonGetter("aname")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getAname() {
        return aname;
    }

    /**
     * Setter for Aname.
     * The name of the billing account for which callback messages will be sent.
     * @param aname Value for String
     */
    @JsonSetter("aname")
    public void setAname(String aname) {
        this.aname = aname;
    }

    /**
     * Getter for Name.
     * The name of the callback service, which identifies the type and format of messages that will
     * be sent to the registered URL. This will be 'Fota' for the Software Management Services
     * callback.
     * @return Returns the String
     */
    @JsonGetter("name")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getName() {
        return name;
    }

    /**
     * Setter for Name.
     * The name of the callback service, which identifies the type and format of messages that will
     * be sent to the registered URL. This will be 'Fota' for the Software Management Services
     * callback.
     * @param name Value for String
     */
    @JsonSetter("name")
    public void setName(String name) {
        this.name = name;
    }

    /**
     * Getter for Url.
     * The address to which callback messages will be sent.
     * @return Returns the String
     */
    @JsonGetter("url")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getUrl() {
        return url;
    }

    /**
     * Setter for Url.
     * The address to which callback messages will be sent.
     * @param url Value for String
     */
    @JsonSetter("url")
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * Getter for Username.
     * The user name that ThingSpace will return in the callback messages.
     * @return Returns the String
     */
    @JsonGetter("username")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getUsername() {
        return username;
    }

    /**
     * Setter for Username.
     * The user name that ThingSpace will return in the callback messages.
     * @param username Value for String
     */
    @JsonSetter("username")
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * Getter for Password.
     * The password that ThingSpace will return in the callback messages.
     * @return Returns the String
     */
    @JsonGetter("password")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getPassword() {
        return password;
    }

    /**
     * Setter for Password.
     * The password that ThingSpace will return in the callback messages.
     * @param password Value for String
     */
    @JsonSetter("password")
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * Converts this RegisteredCallbacks into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "RegisteredCallbacks [" + "aname=" + aname + ", name=" + name + ", url=" + url
                + ", username=" + username + ", password=" + password + "]";
    }

    /**
     * Builds a new {@link RegisteredCallbacks.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link RegisteredCallbacks.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .aname(getAname())
                .name(getName())
                .url(getUrl())
                .username(getUsername())
                .password(getPassword());
        return builder;
    }

    /**
     * Class to build instances of {@link RegisteredCallbacks}.
     */
    public static class Builder {
        private String aname;
        private String name;
        private String url;
        private String username;
        private String password;



        /**
         * Setter for aname.
         * @param  aname  String value for aname.
         * @return Builder
         */
        public Builder aname(String aname) {
            this.aname = aname;
            return this;
        }

        /**
         * Setter for name.
         * @param  name  String value for name.
         * @return Builder
         */
        public Builder name(String name) {
            this.name = name;
            return this;
        }

        /**
         * Setter for url.
         * @param  url  String value for url.
         * @return Builder
         */
        public Builder url(String url) {
            this.url = url;
            return this;
        }

        /**
         * Setter for username.
         * @param  username  String value for username.
         * @return Builder
         */
        public Builder username(String username) {
            this.username = username;
            return this;
        }

        /**
         * Setter for password.
         * @param  password  String value for password.
         * @return Builder
         */
        public Builder password(String password) {
            this.password = password;
            return this;
        }

        /**
         * Builds a new {@link RegisteredCallbacks} object using the set fields.
         * @return {@link RegisteredCallbacks}
         */
        public RegisteredCallbacks build() {
            return new RegisteredCallbacks(aname, name, url, username, password);
        }
    }
}
