/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.verizon.m5gedge.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;

/**
 * This is a model class for SMSMessagesQueryResult type.
 */
public class SMSMessagesQueryResult {
    private Boolean hasMoreData;
    private List<SMSMessage> messages;

    /**
     * Default constructor.
     */
    public SMSMessagesQueryResult() {
    }

    /**
     * Initialization constructor.
     * @param  hasMoreData  Boolean value for hasMoreData.
     * @param  messages  List of SMSMessage value for messages.
     */
    public SMSMessagesQueryResult(
            Boolean hasMoreData,
            List<SMSMessage> messages) {
        this.hasMoreData = hasMoreData;
        this.messages = messages;
    }

    /**
     * Getter for HasMoreData.
     * False for a status 200 response.True for a status 202 response, indicating that there is more
     * data to be retrieved.
     * @return Returns the Boolean
     */
    @JsonGetter("hasMoreData")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Boolean getHasMoreData() {
        return hasMoreData;
    }

    /**
     * Setter for HasMoreData.
     * False for a status 200 response.True for a status 202 response, indicating that there is more
     * data to be retrieved.
     * @param hasMoreData Value for Boolean
     */
    @JsonSetter("hasMoreData")
    public void setHasMoreData(Boolean hasMoreData) {
        this.hasMoreData = hasMoreData;
    }

    /**
     * Getter for Messages.
     * An array of up to 100 SMS messages that were sent by devices in the account.
     * @return Returns the List of SMSMessage
     */
    @JsonGetter("messages")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<SMSMessage> getMessages() {
        return messages;
    }

    /**
     * Setter for Messages.
     * An array of up to 100 SMS messages that were sent by devices in the account.
     * @param messages Value for List of SMSMessage
     */
    @JsonSetter("messages")
    public void setMessages(List<SMSMessage> messages) {
        this.messages = messages;
    }

    /**
     * Converts this SMSMessagesQueryResult into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "SMSMessagesQueryResult [" + "hasMoreData=" + hasMoreData + ", messages=" + messages
                + "]";
    }

    /**
     * Builds a new {@link SMSMessagesQueryResult.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link SMSMessagesQueryResult.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .hasMoreData(getHasMoreData())
                .messages(getMessages());
        return builder;
    }

    /**
     * Class to build instances of {@link SMSMessagesQueryResult}.
     */
    public static class Builder {
        private Boolean hasMoreData;
        private List<SMSMessage> messages;



        /**
         * Setter for hasMoreData.
         * @param  hasMoreData  Boolean value for hasMoreData.
         * @return Builder
         */
        public Builder hasMoreData(Boolean hasMoreData) {
            this.hasMoreData = hasMoreData;
            return this;
        }

        /**
         * Setter for messages.
         * @param  messages  List of SMSMessage value for messages.
         * @return Builder
         */
        public Builder messages(List<SMSMessage> messages) {
            this.messages = messages;
            return this;
        }

        /**
         * Builds a new {@link SMSMessagesQueryResult} object using the set fields.
         * @return {@link SMSMessagesQueryResult}
         */
        public SMSMessagesQueryResult build() {
            return new SMSMessagesQueryResult(hasMoreData, messages);
        }
    }
}
