/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.verizon.m5gedge.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;

/**
 * This is a model class for SMSOptionsSendRequest type.
 */
public class SMSOptionsSendRequest {
    private String servicePlan;
    private String smsMessage;

    /**
     * Default constructor.
     */
    public SMSOptionsSendRequest() {
    }

    /**
     * Initialization constructor.
     * @param  servicePlan  String value for servicePlan.
     * @param  smsMessage  String value for smsMessage.
     */
    public SMSOptionsSendRequest(
            String servicePlan,
            String smsMessage) {
        this.servicePlan = servicePlan;
        this.smsMessage = smsMessage;
    }

    /**
     * Getter for ServicePlan.
     * @return Returns the String
     */
    @JsonGetter("servicePlan")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getServicePlan() {
        return servicePlan;
    }

    /**
     * Setter for ServicePlan.
     * @param servicePlan Value for String
     */
    @JsonSetter("servicePlan")
    public void setServicePlan(String servicePlan) {
        this.servicePlan = servicePlan;
    }

    /**
     * Getter for SmsMessage.
     * @return Returns the String
     */
    @JsonGetter("smsMessage")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getSmsMessage() {
        return smsMessage;
    }

    /**
     * Setter for SmsMessage.
     * @param smsMessage Value for String
     */
    @JsonSetter("smsMessage")
    public void setSmsMessage(String smsMessage) {
        this.smsMessage = smsMessage;
    }

    /**
     * Converts this SMSOptionsSendRequest into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "SMSOptionsSendRequest [" + "servicePlan=" + servicePlan + ", smsMessage="
                + smsMessage + "]";
    }

    /**
     * Builds a new {@link SMSOptionsSendRequest.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link SMSOptionsSendRequest.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .servicePlan(getServicePlan())
                .smsMessage(getSmsMessage());
        return builder;
    }

    /**
     * Class to build instances of {@link SMSOptionsSendRequest}.
     */
    public static class Builder {
        private String servicePlan;
        private String smsMessage;



        /**
         * Setter for servicePlan.
         * @param  servicePlan  String value for servicePlan.
         * @return Builder
         */
        public Builder servicePlan(String servicePlan) {
            this.servicePlan = servicePlan;
            return this;
        }

        /**
         * Setter for smsMessage.
         * @param  smsMessage  String value for smsMessage.
         * @return Builder
         */
        public Builder smsMessage(String smsMessage) {
            this.smsMessage = smsMessage;
            return this;
        }

        /**
         * Builds a new {@link SMSOptionsSendRequest} object using the set fields.
         * @return {@link SMSOptionsSendRequest}
         */
        public SMSOptionsSendRequest build() {
            return new SMSOptionsSendRequest(servicePlan, smsMessage);
        }
    }
}
