/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.verizon.m5gedge.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;

/**
 * This is a model class for SMSSendRequest type.
 */
public class SMSSendRequest {
    private String accountName;
    private String smsMessage;
    private List<CustomFields> customFields;
    private String dataEncoding;
    private List<DeviceId> deviceIds;
    private String groupName;
    private String servicePlan;

    /**
     * Default constructor.
     */
    public SMSSendRequest() {
    }

    /**
     * Initialization constructor.
     * @param  accountName  String value for accountName.
     * @param  smsMessage  String value for smsMessage.
     * @param  customFields  List of CustomFields value for customFields.
     * @param  dataEncoding  String value for dataEncoding.
     * @param  deviceIds  List of DeviceId value for deviceIds.
     * @param  groupName  String value for groupName.
     * @param  servicePlan  String value for servicePlan.
     */
    public SMSSendRequest(
            String accountName,
            String smsMessage,
            List<CustomFields> customFields,
            String dataEncoding,
            List<DeviceId> deviceIds,
            String groupName,
            String servicePlan) {
        this.accountName = accountName;
        this.smsMessage = smsMessage;
        this.customFields = customFields;
        this.dataEncoding = dataEncoding;
        this.deviceIds = deviceIds;
        this.groupName = groupName;
        this.servicePlan = servicePlan;
    }

    /**
     * Getter for AccountName.
     * The name of a billing account.
     * @return Returns the String
     */
    @JsonGetter("accountName")
    public String getAccountName() {
        return accountName;
    }

    /**
     * Setter for AccountName.
     * The name of a billing account.
     * @param accountName Value for String
     */
    @JsonSetter("accountName")
    public void setAccountName(String accountName) {
        this.accountName = accountName;
    }

    /**
     * Getter for SmsMessage.
     * The contents of the SMS message. The SMS message is limited to 160 characters in 7-bit
     * format, or 140 characters in 8-bit format.
     * @return Returns the String
     */
    @JsonGetter("smsMessage")
    public String getSmsMessage() {
        return smsMessage;
    }

    /**
     * Setter for SmsMessage.
     * The contents of the SMS message. The SMS message is limited to 160 characters in 7-bit
     * format, or 140 characters in 8-bit format.
     * @param smsMessage Value for String
     */
    @JsonSetter("smsMessage")
    public void setSmsMessage(String smsMessage) {
        this.smsMessage = smsMessage;
    }

    /**
     * Getter for CustomFields.
     * The names and values of custom fields, if you want to only include devices that have matching
     * custom fields.
     * @return Returns the List of CustomFields
     */
    @JsonGetter("customFields")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<CustomFields> getCustomFields() {
        return customFields;
    }

    /**
     * Setter for CustomFields.
     * The names and values of custom fields, if you want to only include devices that have matching
     * custom fields.
     * @param customFields Value for List of CustomFields
     */
    @JsonSetter("customFields")
    public void setCustomFields(List<CustomFields> customFields) {
        this.customFields = customFields;
    }

    /**
     * Getter for DataEncoding.
     * The SMS message encoding, which can be 7-bit (default), 8-bit-ASCII, 8-bit-UTF-8, 8-bit-DATA.
     * @return Returns the String
     */
    @JsonGetter("dataEncoding")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getDataEncoding() {
        return dataEncoding;
    }

    /**
     * Setter for DataEncoding.
     * The SMS message encoding, which can be 7-bit (default), 8-bit-ASCII, 8-bit-UTF-8, 8-bit-DATA.
     * @param dataEncoding Value for String
     */
    @JsonSetter("dataEncoding")
    public void setDataEncoding(String dataEncoding) {
        this.dataEncoding = dataEncoding;
    }

    /**
     * Getter for DeviceIds.
     * The devices that you want to send the message to, specified by device identifier.
     * @return Returns the List of DeviceId
     */
    @JsonGetter("deviceIds")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<DeviceId> getDeviceIds() {
        return deviceIds;
    }

    /**
     * Setter for DeviceIds.
     * The devices that you want to send the message to, specified by device identifier.
     * @param deviceIds Value for List of DeviceId
     */
    @JsonSetter("deviceIds")
    public void setDeviceIds(List<DeviceId> deviceIds) {
        this.deviceIds = deviceIds;
    }

    /**
     * Getter for GroupName.
     * The name of a device group, if you want to send the SMS message to all devices in the device
     * group.
     * @return Returns the String
     */
    @JsonGetter("groupName")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getGroupName() {
        return groupName;
    }

    /**
     * Setter for GroupName.
     * The name of a device group, if you want to send the SMS message to all devices in the device
     * group.
     * @param groupName Value for String
     */
    @JsonSetter("groupName")
    public void setGroupName(String groupName) {
        this.groupName = groupName;
    }

    /**
     * Getter for ServicePlan.
     * The name of a service plan, if you want to only include devices that have that service plan.
     * @return Returns the String
     */
    @JsonGetter("servicePlan")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getServicePlan() {
        return servicePlan;
    }

    /**
     * Setter for ServicePlan.
     * The name of a service plan, if you want to only include devices that have that service plan.
     * @param servicePlan Value for String
     */
    @JsonSetter("servicePlan")
    public void setServicePlan(String servicePlan) {
        this.servicePlan = servicePlan;
    }

    /**
     * Converts this SMSSendRequest into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "SMSSendRequest [" + "accountName=" + accountName + ", smsMessage=" + smsMessage
                + ", customFields=" + customFields + ", dataEncoding=" + dataEncoding
                + ", deviceIds=" + deviceIds + ", groupName=" + groupName + ", servicePlan="
                + servicePlan + "]";
    }

    /**
     * Builds a new {@link SMSSendRequest.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link SMSSendRequest.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder(accountName, smsMessage)
                .customFields(getCustomFields())
                .dataEncoding(getDataEncoding())
                .deviceIds(getDeviceIds())
                .groupName(getGroupName())
                .servicePlan(getServicePlan());
        return builder;
    }

    /**
     * Class to build instances of {@link SMSSendRequest}.
     */
    public static class Builder {
        private String accountName;
        private String smsMessage;
        private List<CustomFields> customFields;
        private String dataEncoding;
        private List<DeviceId> deviceIds;
        private String groupName;
        private String servicePlan;

        /**
         * Initialization constructor.
         */
        public Builder() {
        }

        /**
         * Initialization constructor.
         * @param  accountName  String value for accountName.
         * @param  smsMessage  String value for smsMessage.
         */
        public Builder(String accountName, String smsMessage) {
            this.accountName = accountName;
            this.smsMessage = smsMessage;
        }

        /**
         * Setter for accountName.
         * @param  accountName  String value for accountName.
         * @return Builder
         */
        public Builder accountName(String accountName) {
            this.accountName = accountName;
            return this;
        }

        /**
         * Setter for smsMessage.
         * @param  smsMessage  String value for smsMessage.
         * @return Builder
         */
        public Builder smsMessage(String smsMessage) {
            this.smsMessage = smsMessage;
            return this;
        }

        /**
         * Setter for customFields.
         * @param  customFields  List of CustomFields value for customFields.
         * @return Builder
         */
        public Builder customFields(List<CustomFields> customFields) {
            this.customFields = customFields;
            return this;
        }

        /**
         * Setter for dataEncoding.
         * @param  dataEncoding  String value for dataEncoding.
         * @return Builder
         */
        public Builder dataEncoding(String dataEncoding) {
            this.dataEncoding = dataEncoding;
            return this;
        }

        /**
         * Setter for deviceIds.
         * @param  deviceIds  List of DeviceId value for deviceIds.
         * @return Builder
         */
        public Builder deviceIds(List<DeviceId> deviceIds) {
            this.deviceIds = deviceIds;
            return this;
        }

        /**
         * Setter for groupName.
         * @param  groupName  String value for groupName.
         * @return Builder
         */
        public Builder groupName(String groupName) {
            this.groupName = groupName;
            return this;
        }

        /**
         * Setter for servicePlan.
         * @param  servicePlan  String value for servicePlan.
         * @return Builder
         */
        public Builder servicePlan(String servicePlan) {
            this.servicePlan = servicePlan;
            return this;
        }

        /**
         * Builds a new {@link SMSSendRequest} object using the set fields.
         * @return {@link SMSSendRequest}
         */
        public SMSSendRequest build() {
            return new SMSSendRequest(accountName, smsMessage, customFields, dataEncoding,
                    deviceIds, groupName, servicePlan);
        }
    }
}
