/*
 * VerizonLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

package com.verizon.m5gedge.models;

import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonSetter;
import java.util.List;

/**
 * This is a model class for ThingspaceDevice type.
 */
public class ThingspaceDevice {
    private String accountName;
    private String billingCycleEndDate;
    private List<CarrierInformation> carrierInformations;
    private Boolean connected;
    private String createdAt;
    private List<CustomFields> customFields;
    private List<DeviceId> deviceIds;
    private List<CustomFields> extendedAttributes;
    private List<String> groupNames;
    private String ipAddress;
    private String lastActivationBy;
    private String lastActivationDate;
    private String lastConnectionDate;

    /**
     * Default constructor.
     */
    public ThingspaceDevice() {
    }

    /**
     * Initialization constructor.
     * @param  accountName  String value for accountName.
     * @param  billingCycleEndDate  String value for billingCycleEndDate.
     * @param  carrierInformations  List of CarrierInformation value for carrierInformations.
     * @param  connected  Boolean value for connected.
     * @param  createdAt  String value for createdAt.
     * @param  customFields  List of CustomFields value for customFields.
     * @param  deviceIds  List of DeviceId value for deviceIds.
     * @param  extendedAttributes  List of CustomFields value for extendedAttributes.
     * @param  groupNames  List of String value for groupNames.
     * @param  ipAddress  String value for ipAddress.
     * @param  lastActivationBy  String value for lastActivationBy.
     * @param  lastActivationDate  String value for lastActivationDate.
     * @param  lastConnectionDate  String value for lastConnectionDate.
     */
    public ThingspaceDevice(
            String accountName,
            String billingCycleEndDate,
            List<CarrierInformation> carrierInformations,
            Boolean connected,
            String createdAt,
            List<CustomFields> customFields,
            List<DeviceId> deviceIds,
            List<CustomFields> extendedAttributes,
            List<String> groupNames,
            String ipAddress,
            String lastActivationBy,
            String lastActivationDate,
            String lastConnectionDate) {
        this.accountName = accountName;
        this.billingCycleEndDate = billingCycleEndDate;
        this.carrierInformations = carrierInformations;
        this.connected = connected;
        this.createdAt = createdAt;
        this.customFields = customFields;
        this.deviceIds = deviceIds;
        this.extendedAttributes = extendedAttributes;
        this.groupNames = groupNames;
        this.ipAddress = ipAddress;
        this.lastActivationBy = lastActivationBy;
        this.lastActivationDate = lastActivationDate;
        this.lastConnectionDate = lastConnectionDate;
    }

    /**
     * Getter for AccountName.
     * The billing account that the device is associated with.
     * @return Returns the String
     */
    @JsonGetter("accountName")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getAccountName() {
        return accountName;
    }

    /**
     * Setter for AccountName.
     * The billing account that the device is associated with.
     * @param accountName Value for String
     */
    @JsonSetter("accountName")
    public void setAccountName(String accountName) {
        this.accountName = accountName;
    }

    /**
     * Getter for BillingCycleEndDate.
     * The date that the device's current billing cycle ends.
     * @return Returns the String
     */
    @JsonGetter("billingCycleEndDate")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getBillingCycleEndDate() {
        return billingCycleEndDate;
    }

    /**
     * Setter for BillingCycleEndDate.
     * The date that the device's current billing cycle ends.
     * @param billingCycleEndDate Value for String
     */
    @JsonSetter("billingCycleEndDate")
    public void setBillingCycleEndDate(String billingCycleEndDate) {
        this.billingCycleEndDate = billingCycleEndDate;
    }

    /**
     * Getter for CarrierInformations.
     * The carrier information associated with the device.
     * @return Returns the List of CarrierInformation
     */
    @JsonGetter("carrierInformations")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<CarrierInformation> getCarrierInformations() {
        return carrierInformations;
    }

    /**
     * Setter for CarrierInformations.
     * The carrier information associated with the device.
     * @param carrierInformations Value for List of CarrierInformation
     */
    @JsonSetter("carrierInformations")
    public void setCarrierInformations(List<CarrierInformation> carrierInformations) {
        this.carrierInformations = carrierInformations;
    }

    /**
     * Getter for Connected.
     * True if the device is connected; false if it is not.
     * @return Returns the Boolean
     */
    @JsonGetter("connected")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public Boolean getConnected() {
        return connected;
    }

    /**
     * Setter for Connected.
     * True if the device is connected; false if it is not.
     * @param connected Value for Boolean
     */
    @JsonSetter("connected")
    public void setConnected(Boolean connected) {
        this.connected = connected;
    }

    /**
     * Getter for CreatedAt.
     * The date and time that the device was added to the system.
     * @return Returns the String
     */
    @JsonGetter("createdAt")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getCreatedAt() {
        return createdAt;
    }

    /**
     * Setter for CreatedAt.
     * The date and time that the device was added to the system.
     * @param createdAt Value for String
     */
    @JsonSetter("createdAt")
    public void setCreatedAt(String createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * Getter for CustomFields.
     * The custom fields and values that have been set for the device.
     * @return Returns the List of CustomFields
     */
    @JsonGetter("customFields")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<CustomFields> getCustomFields() {
        return customFields;
    }

    /**
     * Setter for CustomFields.
     * The custom fields and values that have been set for the device.
     * @param customFields Value for List of CustomFields
     */
    @JsonSetter("customFields")
    public void setCustomFields(List<CustomFields> customFields) {
        this.customFields = customFields;
    }

    /**
     * Getter for DeviceIds.
     * All identifiers for the device.
     * @return Returns the List of DeviceId
     */
    @JsonGetter("deviceIds")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<DeviceId> getDeviceIds() {
        return deviceIds;
    }

    /**
     * Setter for DeviceIds.
     * All identifiers for the device.
     * @param deviceIds Value for List of DeviceId
     */
    @JsonSetter("deviceIds")
    public void setDeviceIds(List<DeviceId> deviceIds) {
        this.deviceIds = deviceIds;
    }

    /**
     * Getter for ExtendedAttributes.
     * Any extended attributes for the device, as Key and Value pairs. The pairs listed below are
     * returned as part of the response for a single device, but are not included if the request was
     * for information about multiple devices.
     * @return Returns the List of CustomFields
     */
    @JsonGetter("extendedAttributes")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<CustomFields> getExtendedAttributes() {
        return extendedAttributes;
    }

    /**
     * Setter for ExtendedAttributes.
     * Any extended attributes for the device, as Key and Value pairs. The pairs listed below are
     * returned as part of the response for a single device, but are not included if the request was
     * for information about multiple devices.
     * @param extendedAttributes Value for List of CustomFields
     */
    @JsonSetter("extendedAttributes")
    public void setExtendedAttributes(List<CustomFields> extendedAttributes) {
        this.extendedAttributes = extendedAttributes;
    }

    /**
     * Getter for GroupNames.
     * The device groups that the device belongs to.
     * @return Returns the List of String
     */
    @JsonGetter("groupNames")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public List<String> getGroupNames() {
        return groupNames;
    }

    /**
     * Setter for GroupNames.
     * The device groups that the device belongs to.
     * @param groupNames Value for List of String
     */
    @JsonSetter("groupNames")
    public void setGroupNames(List<String> groupNames) {
        this.groupNames = groupNames;
    }

    /**
     * Getter for IpAddress.
     * The IP address of the device.
     * @return Returns the String
     */
    @JsonGetter("ipAddress")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getIpAddress() {
        return ipAddress;
    }

    /**
     * Setter for IpAddress.
     * The IP address of the device.
     * @param ipAddress Value for String
     */
    @JsonSetter("ipAddress")
    public void setIpAddress(String ipAddress) {
        this.ipAddress = ipAddress;
    }

    /**
     * Getter for LastActivationBy.
     * The user who last activated the device.
     * @return Returns the String
     */
    @JsonGetter("lastActivationBy")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getLastActivationBy() {
        return lastActivationBy;
    }

    /**
     * Setter for LastActivationBy.
     * The user who last activated the device.
     * @param lastActivationBy Value for String
     */
    @JsonSetter("lastActivationBy")
    public void setLastActivationBy(String lastActivationBy) {
        this.lastActivationBy = lastActivationBy;
    }

    /**
     * Getter for LastActivationDate.
     * The date and time that the device was last activated.
     * @return Returns the String
     */
    @JsonGetter("lastActivationDate")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getLastActivationDate() {
        return lastActivationDate;
    }

    /**
     * Setter for LastActivationDate.
     * The date and time that the device was last activated.
     * @param lastActivationDate Value for String
     */
    @JsonSetter("lastActivationDate")
    public void setLastActivationDate(String lastActivationDate) {
        this.lastActivationDate = lastActivationDate;
    }

    /**
     * Getter for LastConnectionDate.
     * The most recent connection date and time.
     * @return Returns the String
     */
    @JsonGetter("lastConnectionDate")
    @JsonInclude(JsonInclude.Include.NON_NULL)
    public String getLastConnectionDate() {
        return lastConnectionDate;
    }

    /**
     * Setter for LastConnectionDate.
     * The most recent connection date and time.
     * @param lastConnectionDate Value for String
     */
    @JsonSetter("lastConnectionDate")
    public void setLastConnectionDate(String lastConnectionDate) {
        this.lastConnectionDate = lastConnectionDate;
    }

    /**
     * Converts this ThingspaceDevice into string format.
     * @return String representation of this class
     */
    @Override
    public String toString() {
        return "ThingspaceDevice [" + "accountName=" + accountName + ", billingCycleEndDate="
                + billingCycleEndDate + ", carrierInformations=" + carrierInformations
                + ", connected=" + connected + ", createdAt=" + createdAt + ", customFields="
                + customFields + ", deviceIds=" + deviceIds + ", extendedAttributes="
                + extendedAttributes + ", groupNames=" + groupNames + ", ipAddress=" + ipAddress
                + ", lastActivationBy=" + lastActivationBy + ", lastActivationDate="
                + lastActivationDate + ", lastConnectionDate=" + lastConnectionDate + "]";
    }

    /**
     * Builds a new {@link ThingspaceDevice.Builder} object.
     * Creates the instance with the state of the current model.
     * @return a new {@link ThingspaceDevice.Builder} object
     */
    public Builder toBuilder() {
        Builder builder = new Builder()
                .accountName(getAccountName())
                .billingCycleEndDate(getBillingCycleEndDate())
                .carrierInformations(getCarrierInformations())
                .connected(getConnected())
                .createdAt(getCreatedAt())
                .customFields(getCustomFields())
                .deviceIds(getDeviceIds())
                .extendedAttributes(getExtendedAttributes())
                .groupNames(getGroupNames())
                .ipAddress(getIpAddress())
                .lastActivationBy(getLastActivationBy())
                .lastActivationDate(getLastActivationDate())
                .lastConnectionDate(getLastConnectionDate());
        return builder;
    }

    /**
     * Class to build instances of {@link ThingspaceDevice}.
     */
    public static class Builder {
        private String accountName;
        private String billingCycleEndDate;
        private List<CarrierInformation> carrierInformations;
        private Boolean connected;
        private String createdAt;
        private List<CustomFields> customFields;
        private List<DeviceId> deviceIds;
        private List<CustomFields> extendedAttributes;
        private List<String> groupNames;
        private String ipAddress;
        private String lastActivationBy;
        private String lastActivationDate;
        private String lastConnectionDate;



        /**
         * Setter for accountName.
         * @param  accountName  String value for accountName.
         * @return Builder
         */
        public Builder accountName(String accountName) {
            this.accountName = accountName;
            return this;
        }

        /**
         * Setter for billingCycleEndDate.
         * @param  billingCycleEndDate  String value for billingCycleEndDate.
         * @return Builder
         */
        public Builder billingCycleEndDate(String billingCycleEndDate) {
            this.billingCycleEndDate = billingCycleEndDate;
            return this;
        }

        /**
         * Setter for carrierInformations.
         * @param  carrierInformations  List of CarrierInformation value for carrierInformations.
         * @return Builder
         */
        public Builder carrierInformations(List<CarrierInformation> carrierInformations) {
            this.carrierInformations = carrierInformations;
            return this;
        }

        /**
         * Setter for connected.
         * @param  connected  Boolean value for connected.
         * @return Builder
         */
        public Builder connected(Boolean connected) {
            this.connected = connected;
            return this;
        }

        /**
         * Setter for createdAt.
         * @param  createdAt  String value for createdAt.
         * @return Builder
         */
        public Builder createdAt(String createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        /**
         * Setter for customFields.
         * @param  customFields  List of CustomFields value for customFields.
         * @return Builder
         */
        public Builder customFields(List<CustomFields> customFields) {
            this.customFields = customFields;
            return this;
        }

        /**
         * Setter for deviceIds.
         * @param  deviceIds  List of DeviceId value for deviceIds.
         * @return Builder
         */
        public Builder deviceIds(List<DeviceId> deviceIds) {
            this.deviceIds = deviceIds;
            return this;
        }

        /**
         * Setter for extendedAttributes.
         * @param  extendedAttributes  List of CustomFields value for extendedAttributes.
         * @return Builder
         */
        public Builder extendedAttributes(List<CustomFields> extendedAttributes) {
            this.extendedAttributes = extendedAttributes;
            return this;
        }

        /**
         * Setter for groupNames.
         * @param  groupNames  List of String value for groupNames.
         * @return Builder
         */
        public Builder groupNames(List<String> groupNames) {
            this.groupNames = groupNames;
            return this;
        }

        /**
         * Setter for ipAddress.
         * @param  ipAddress  String value for ipAddress.
         * @return Builder
         */
        public Builder ipAddress(String ipAddress) {
            this.ipAddress = ipAddress;
            return this;
        }

        /**
         * Setter for lastActivationBy.
         * @param  lastActivationBy  String value for lastActivationBy.
         * @return Builder
         */
        public Builder lastActivationBy(String lastActivationBy) {
            this.lastActivationBy = lastActivationBy;
            return this;
        }

        /**
         * Setter for lastActivationDate.
         * @param  lastActivationDate  String value for lastActivationDate.
         * @return Builder
         */
        public Builder lastActivationDate(String lastActivationDate) {
            this.lastActivationDate = lastActivationDate;
            return this;
        }

        /**
         * Setter for lastConnectionDate.
         * @param  lastConnectionDate  String value for lastConnectionDate.
         * @return Builder
         */
        public Builder lastConnectionDate(String lastConnectionDate) {
            this.lastConnectionDate = lastConnectionDate;
            return this;
        }

        /**
         * Builds a new {@link ThingspaceDevice} object using the set fields.
         * @return {@link ThingspaceDevice}
         */
        public ThingspaceDevice build() {
            return new ThingspaceDevice(accountName, billingCycleEndDate, carrierInformations,
                    connected, createdAt, customFields, deviceIds, extendedAttributes, groupNames,
                    ipAddress, lastActivationBy, lastActivationDate, lastConnectionDate);
        }
    }
}
